
USE [AOSData]
GO

/****** Object:  StoredProcedure [dbo].[proc_COMMISSIONLoadByPrimaryKey] Script Date: 12/10/2013 4:01:04 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_COMMISSIONLoadByPrimaryKey]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_COMMISSIONLoadByPrimaryKey];
GO

CREATE PROCEDURE [dbo].[proc_COMMISSIONLoadByPrimaryKey]
(
	@COMMISSIONID int
)
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @Err int

	SELECT
		[COMMISSIONID], 
		[COMMISSIONDATE], 
		[SALESPERSONID], 
		[CUSTID], 
		[INVOICENUMBER], 
		[COMMISSIONAMOUNT], 
		[COMMISSIONSTATUS], 
		[COMMISSIONDESC], 
		[COMMISSIONTYPE], 
		[DATECUSTOMERPAID], 
		[DATECOMMISSIONPAID], 
		[COMMISSIONPMTID], 
		[COMMISSIONNOTE], 
		[COMMISSIONCATEGORY]
	FROM [dbo].[COMMISSION]
	WHERE
		([COMMISSIONID] = @COMMISSIONID)

	SET @Err = @@Error

	RETURN @Err
END
GO	


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_COMMISSIONLoadByPrimaryKey Succeeded'
ELSE PRINT 'Procedure Creation: proc_COMMISSIONLoadByPrimaryKey Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_COMMISSIONLoadAll] Script Date: 12/10/2013 4:01:04 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_COMMISSIONLoadAll]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_COMMISSIONLoadAll];
GO

CREATE PROCEDURE [dbo].[proc_COMMISSIONLoadAll]
AS
BEGIN

	SET NOCOUNT ON
	DECLARE @Err int

	SELECT
		[COMMISSIONID], 
		[COMMISSIONDATE], 
		[SALESPERSONID], 
		[CUSTID], 
		[INVOICENUMBER], 
		[COMMISSIONAMOUNT], 
		[COMMISSIONSTATUS], 
		[COMMISSIONDESC], 
		[COMMISSIONTYPE], 
		[DATECUSTOMERPAID], 
		[DATECOMMISSIONPAID], 
		[COMMISSIONPMTID], 
		[COMMISSIONNOTE], 
		[COMMISSIONCATEGORY]
	FROM [dbo].[COMMISSION]

	SET @Err = @@Error

	RETURN @Err
END
GO


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_COMMISSIONLoadAll Succeeded'
ELSE PRINT 'Procedure Creation: proc_COMMISSIONLoadAll Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_COMMISSIONUpdate] Script Date: 12/10/2013 4:01:04 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_COMMISSIONUpdate]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_COMMISSIONUpdate];
GO

CREATE PROCEDURE [dbo].[proc_COMMISSIONUpdate]
(
	@COMMISSIONID int, 
	@COMMISSIONDATE datetime = NULL, 
	@SALESPERSONID int = NULL, 
	@CUSTID int = NULL, 
	@INVOICENUMBER int = NULL, 
	@COMMISSIONAMOUNT money = NULL, 
	@COMMISSIONSTATUS varchar(50) = NULL, 
	@COMMISSIONDESC varchar(200) = NULL, 
	@COMMISSIONTYPE varchar(50) = NULL, 
	@DATECUSTOMERPAID datetime = NULL, 
	@DATECOMMISSIONPAID datetime = NULL, 
	@COMMISSIONPMTID int = NULL, 
	@COMMISSIONNOTE varchar(200) = NULL, 
	@COMMISSIONCATEGORY varchar(50) = NULL
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	UPDATE [COMMISSION]
	SET
		[COMMISSIONDATE] = @COMMISSIONDATE, 
		[SALESPERSONID] = @SALESPERSONID, 
		[CUSTID] = @CUSTID, 
		[INVOICENUMBER] = @INVOICENUMBER, 
		[COMMISSIONAMOUNT] = @COMMISSIONAMOUNT, 
		[COMMISSIONSTATUS] = @COMMISSIONSTATUS, 
		[COMMISSIONDESC] = @COMMISSIONDESC, 
		[COMMISSIONTYPE] = @COMMISSIONTYPE, 
		[DATECUSTOMERPAID] = @DATECUSTOMERPAID, 
		[DATECOMMISSIONPAID] = @DATECOMMISSIONPAID, 
		[COMMISSIONPMTID] = @COMMISSIONPMTID, 
		[COMMISSIONNOTE] = @COMMISSIONNOTE, 
		[COMMISSIONCATEGORY] = @COMMISSIONCATEGORY
	WHERE
		([COMMISSIONID] = @COMMISSIONID)

	SET @Err = @@Error


	RETURN @Err
END
GO



-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_COMMISSIONUpdate Succeeded'
ELSE PRINT 'Procedure Creation: proc_COMMISSIONUpdate Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_COMMISSIONInsert] Script Date: 12/10/2013 4:01:04 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_COMMISSIONInsert]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_COMMISSIONInsert];
GO

CREATE PROCEDURE [dbo].[proc_COMMISSIONInsert]
(
	@COMMISSIONID int = NULL OUTPUT, 
	@COMMISSIONDATE datetime = NULL, 
	@SALESPERSONID int = NULL, 
	@CUSTID int = NULL, 
	@INVOICENUMBER int = NULL, 
	@COMMISSIONAMOUNT money = NULL, 
	@COMMISSIONSTATUS varchar(50) = NULL, 
	@COMMISSIONDESC varchar(200) = NULL, 
	@COMMISSIONTYPE varchar(50) = NULL, 
	@DATECUSTOMERPAID datetime = NULL, 
	@DATECOMMISSIONPAID datetime = NULL, 
	@COMMISSIONPMTID int = NULL, 
	@COMMISSIONNOTE varchar(200) = NULL, 
	@COMMISSIONCATEGORY varchar(50) = NULL
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int
	

	INSERT
	INTO [COMMISSION]
	(
		[COMMISSIONDATE], 
		[SALESPERSONID], 
		[CUSTID], 
		[INVOICENUMBER], 
		[COMMISSIONAMOUNT], 
		[COMMISSIONSTATUS], 
		[COMMISSIONDESC], 
		[COMMISSIONTYPE], 
		[DATECUSTOMERPAID], 
		[DATECOMMISSIONPAID], 
		[COMMISSIONPMTID], 
		[COMMISSIONNOTE], 
		[COMMISSIONCATEGORY]
	)
	
	VALUES
	(
		@COMMISSIONDATE, 
		@SALESPERSONID, 
		@CUSTID, 
		@INVOICENUMBER, 
		@COMMISSIONAMOUNT, 
		@COMMISSIONSTATUS, 
		@COMMISSIONDESC, 
		@COMMISSIONTYPE, 
		@DATECUSTOMERPAID, 
		@DATECOMMISSIONPAID, 
		@COMMISSIONPMTID, 
		@COMMISSIONNOTE, 
		@COMMISSIONCATEGORY
	)

	SET @Err = @@Error

		
	SELECT @COMMISSIONID = SCOPE_IDENTITY()

	

	RETURN @Err
END
GO


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_COMMISSIONInsert Succeeded'
ELSE PRINT 'Procedure Creation: proc_COMMISSIONInsert Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_COMMISSIONDelete] Script Date: 12/10/2013 4:01:04 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_COMMISSIONDelete]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_COMMISSIONDelete];
GO

CREATE PROCEDURE [dbo].[proc_COMMISSIONDelete]
(
	@COMMISSIONID int
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	DELETE
	FROM [dbo].[COMMISSION]
	WHERE
		([COMMISSIONID] = @COMMISSIONID)

	SET @Err = @@Error

	RETURN @Err
END
GO


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_COMMISSIONDelete Succeeded'
ELSE PRINT 'Procedure Creation: proc_COMMISSIONDelete Error on Creation'
GO 

