-- INSERT ALL FUNCTIONS
SET IDENTITY_INSERT [APPFUNCTION] ON;

MERGE INTO [APPFUNCTION] As Target
USING (VALUES
		(358, 'Open Orders', '', GETDATE(), GETDATE(), 135,0),
		(359, 'Completed Orders', '', GETDATE(), GETDATE(), 135,0),
		(361, 'Relabeled Products List', '', GETDATE(), GETDATE(), 135,0),
		(362, 'Retrieve All Orders', '', GETDATE(), GETDATE(), 135, 0),
		(363, 'Edit Order', '', GETDATE(), GETDATE(), 135, 0),
		(364, 'Cancel Order', '', GETDATE(), GETDATE(), 135, 0),
		(365, 'Print Order', '', GETDATE(), GETDATE(), 135, 0),
		(366, 'Cancelled Orders', '', GETDATE(), GETDATE(), 135, 0),
		(367, 'Print Relabel Orders Summary', '', GETDATE(), GETDATE(), 135, 0)
) AS Source (
	[APPFUNCTIONID],
	[APPFUNCTIONNAME], 
	[APPFUNCTIONDESC], 
	[DATEADDED], 
	[DATEUPDATED], 
	[APPGROUPID], 
	[PERMITTEDBYDEFAULT] )
		ON (Target.[APPFUNCTIONID] = Source.[APPFUNCTIONID])
	WHEN MATCHED THEN 
		UPDATE SET 
			Target.[APPFUNCTIONNAME] = Source.[APPFUNCTIONNAME],
			Target.[APPFUNCTIONDESC] = Source.[APPFUNCTIONDESC],
			Target.[DATEUPDATED] = Source.[DATEUPDATED],
			Target.[APPGROUPID] = Source.[APPGROUPID],
			Target.[PERMITTEDBYDEFAULT] = Source.[PERMITTEDBYDEFAULT]
	WHEN NOT MATCHED BY TARGET THEN
		INSERT  (
				[APPFUNCTIONID],
				[APPFUNCTIONNAME], 
				[APPFUNCTIONDESC], 
				[DATEADDED], 
				[DATEUPDATED], 
				[APPGROUPID], 
				[PERMITTEDBYDEFAULT] )
			VALUES (
				Source.[APPFUNCTIONID],
				Source.[APPFUNCTIONNAME], 
				Source.[APPFUNCTIONDESC], 
				Source.[DATEADDED], 
				Source.[DATEUPDATED], 
				Source.[APPGROUPID], 
				Source.[PERMITTEDBYDEFAULT] );

SET IDENTITY_INSERT [APPFUNCTION] OFF;

--CREATE PERMISSIONS ROWS FOR ALL USERS
MERGE INTO [APPUSERFUNCTION] As Target
USING (
	SELECT 
			AU.[APPUSERID],
			AF.[APPFUNCTIONID],
			GETDATE(),
			GETDATE(),
			CASE 
				WHEN AU.[USERSECURITYLEVEL] = 10
					THEN 1
				ELSE 0
			END AS [PERMITTED]
		FROM APPUSER AS AU
			LEFT JOIN APPFUNCTION AF
				ON AF.[APPGROUPID] = 135
					AND AF.[APPFUNCTIONID] IN ( 358, 359, 361, 362, 363, 364, 365, 366, 367 )
	) AS Source (
			[APPUSERID], 
			[APPFUNCTIONID], 
			[DATEADDED], 
			[DATEUPDATED], 
			[PERMITTED])
	ON Target.[APPFUNCTIONID] = Source.[APPFUNCTIONID]
		AND Target.[APPUSERID] = Source.[APPUSERID]

	WHEN MATCHED THEN
		UPDATE SET 
			Target.[DATEUPDATED] = Source.[DATEUPDATED],
			Target.[PERMITTED] = Source.[PERMITTED]
	WHEN NOT MATCHED BY Target THEN
		INSERT (
				[APPUSERID], 
				[APPFUNCTIONID], 
				[DATEADDED], 
				[DATEUPDATED], 
				[PERMITTED])
			VALUES (
				Source.[APPUSERID], 
				Source.[APPFUNCTIONID], 
				Source.[DATEADDED], 
				Source.[DATEUPDATED], 
				Source.[PERMITTED]);
