
use [AOSTEST]
/************************* COSTMETHOD *************************/
IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'COSTMETHOD' AND [object_id] = OBJECT_ID(N'PRODUCTCOST'))
BEGIN
	ALTER TABLE [PRODUCTCOST] ADD [COSTMETHOD] VARCHAR (50)
END
GO

--------------14.50 Release ----------------

/****** Object:  Table [dbo].[LIST_FULFILLMENTTYPE]   ******/
IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'LIST_FULFILLMENTTYPE'))
BEGIN
CREATE TABLE [dbo].[LIST_FULFILLMENTTYPE](
	[FULFILLMENTTYPEID] [int] NOT NULL,
	[FULFILLMENTTYPE] [varchar](10) NOT NULL,
	[DESCRIPTION] [varchar](200) NULL,
	[CREATEDBY] [varchar](50) NOT NULL,
	[CREATEDTIME] [datetime] NOT NULL,
	[MODIFYBY] [varchar](50) NULL,
	[MODIFYTIME] [datetime] NULL,
 CONSTRAINT [PK_LIST_FULFILLMENTTYPE] PRIMARY KEY CLUSTERED 
(
	[FULFILLMENTTYPEID] 
)) 
END
GO


/****** Object:  Table [dbo].[PRODUCTFULFILLMENTPLAN]   ******/
IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'PRODUCTFULFILLMENTPLAN'))
BEGIN
CREATE TABLE [dbo].[PRODUCTFULFILLMENTPLAN](
	[FULFILLMENTPLANID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCTID] [int] NULL,
	[FULFILLMENTTYPEID] [int] NOT NULL,
	[PRIORITY] [int] NOT NULL CONSTRAINT [DF_PRODUCTFULFILLMENTPLAN_PRIORITY] DEFAULT 0,
	[ASSOCIATEDPRODUCTID] [int] NULL,
	[CREATEDBY] [varchar](50) NOT NULL,
	[CREATEDTIME] [datetime] NOT NULL,
	[MODIFYBY] [varchar](50) NULL,
	[MODIFYTIME] [datetime] NULL,
 CONSTRAINT [PK_PRODUCTFULFILLMENTPLAN] PRIMARY KEY CLUSTERED 
(
	[FULFILLMENTPLANID] ASC
))
END
GO

IF EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'PURCHASE'))
BEGIN
	DROP TABLE PURCHASE
END
GO

/****** Object:  Table [dbo].[PURCHASE] ******/
IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'PURCHASE'))
BEGIN
CREATE TABLE [dbo].[PURCHASE](
	[PURCHASENUMBER] [int] IDENTITY(1,1) NOT NULL,
	[VENDORID] [int] NULL,
	[PURCHASEDATE] [datetime] NOT NULL,
	[PURCHASETYPE] [varchar](10) NOT NULL,
	[TERMS] [varchar](50) NULL,
	[PURCHASESTATUS] [varchar](50) NOT NULL,
	[CUSTOMERPO] [varchar](50) NULL,
	[SHIPNAME] [varchar](50) NULL,
	[SHIPADDRESS1] [varchar](50) NULL,
	[SHIPADDRESS2] [varchar](50) NULL,
	[SHIPCITY] [varchar](50) NULL,
	[SHIPSTATE] [varchar](50) NULL,
	[SHIPZIP] [varchar](10) NULL,
	[SHIPCONTACT] [varchar](50) NULL,
	[SHIPPHONE] [varchar](20) NULL,
	[SUBTOTAL] DECIMAL(18,4) NOT NULL,
	[SALESTAX] DECIMAL(18,4) NOT NULL,
	[FREIGHTIN] DECIMAL(18,4) NOT NULL,
	[TOTAL] DECIMAL(18,4) NOT NULL,
	[INSTRUCTIONS] [varchar](max) NULL,
	[CUSTID] [int] NULL,
	[EXPECTEDINDATE] [datetime] NULL,
	[CREATEDBY] [varchar](50) NOT NULL,
	[CREATEDTIME] [datetime] NOT NULL,
	[MODIFYBY] [varchar](50) NULL,
	[MODIFYTIME] [datetime] NULL,
 CONSTRAINT [PK_PURCHASE] PRIMARY KEY CLUSTERED 
(
	[PURCHASENUMBER] ASC
))
END
GO

DBCC CHECKIDENT ('[PURCHASE]', RESEED, 10001) 
GO

/****** Object:  Table [dbo].[PURCHASEITEMHISTORY] ******/
IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'PURCHASEITEMHISTORY'))
BEGIN
CREATE TABLE [dbo].[PURCHASEITEMHISTORY](
	[PURCHASEITEMHISTORYID] [int] IDENTITY(1,1) NOT NULL,
	[PURCHASEITEMID] [int] NOT NULL,
	[PURCHASESTATUS] [varchar](50) NOT NULL,
	[PURCHASETYPE] [varchar](20) NOT NULL,
	[ITEMID] [int] NOT NULL,
	[ITEMTYPE] [varchar](50) NOT NULL,
	[ITEMDESCRIPTION] [varchar](200) NULL,
	[QTY] [numeric](18, 4) NOT NULL,
	[UNITORCONTAINER] [varchar](1) NOT NULL,
	[CONTAINER] [varchar](50) NULL,
	[UNITSINCONTAINER] [int] NULL,
	[UOM] [varchar](50) NULL,
	[UNITCOST] [decimal](18, 4) NULL,
	[DATENEEDED] [datetime] NOT NULL,
	[VENDORID] [int] NOT NULL,
	[CUSTOMERID] [int] NULL,
	[PURCHASENUMBER] [int] NULL,
	[CREATEDBY] [varchar](50) NOT NULL,
	[CREATEDTIME] [datetime] NOT NULL,
 CONSTRAINT [PK_PURCHASEITEMHISTORY] PRIMARY KEY CLUSTERED 
(
	[PURCHASEITEMHISTORYID] ASC
))
END

GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'RESTRICTEDTOCUSTOMERID' AND [object_id] = OBJECT_ID(N'PRODUCTCOST'))
BEGIN
    ALTER TABLE PRODUCTCOST ADD RESTRICTEDTOCUSTOMERID INT NULL
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'COSTTYPE' AND [object_id] = OBJECT_ID(N'PRODUCTCOST'))
BEGIN
    ALTER TABLE PRODUCTCOST ADD COSTTYPE VARCHAR(10) NULL
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'PRIORITY' AND [object_id] = OBJECT_ID(N'MATERIALPRODUCT'))
BEGIN
    ALTER TABLE MATERIALPRODUCT ADD [PRIORITY] INT NULL
END
GO

IF NOT EXISTS(SELECT * FROM sys.objects WHERE   [object_id] = OBJECT_ID(N'DF_MATERIALPRODUCT_PRIORITY'))
BEGIN
    ALTER TABLE MATERIALPRODUCT ADD CONSTRAINT [DF_MATERIALPRODUCT_PRIORITY] DEFAULT 0 FOR [PRIORITY]
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'LIST_COSTTYPE'))
BEGIN
	CREATE TABLE [dbo].[LIST_COSTTYPE](
		[RecID] [int] NOT NULL,
		[COSTTYPE] [varchar](10) NULL,
	 CONSTRAINT [PK_LIST_COSTTYPE] PRIMARY KEY CLUSTERED 
	(
		[RecID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO


-------------------------- Release 14.50 - 12/05/2014 ---------

-- DELETE FROM purchase
-- DELETE FROM purchaseItem

--DBCC CHECKIDENT ('PURCHASEITEM', RESEED, 1000)
--GO
--DBCC CHECKIDENT ('PURCHASE', RESEED, 1000)
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'SOURCEDOCUMENT' AND [object_id] = OBJECT_ID(N'INVITEM'))
BEGIN
    ALTER TABLE INVITEM ADD [SOURCEDOCUMENT] [INT] NULL
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'SOURCETYPE' AND [object_id] = OBJECT_ID(N'INVITEM'))
BEGIN
    ALTER TABLE INVITEM ADD [SOURCETYPE] [varchar](50) NULL
END
GO

--IF EXISTS(SELECT * FROM sys.columns WHERE [name] = N'REQUESTEDVENDORID' AND [object_id] = OBJECT_ID(N'PURCHASEITEM'))
--BEGIN
--    ALTER TABLE PURCHASEITEM DROP COLUMN REQUESTEDVENDORID
--END
--GO

--IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'VENDORITEMNUMBER' AND [object_id] = OBJECT_ID(N'PURCHASEITEM'))
--BEGIN
--    ALTER TABLE PURCHASEITEM ADD [VENDORITEMNUMBER] [varchar](50) NULL
--END
--GO

--------------14.504 Release ----------------

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'ORDERSTATUS' AND [object_id] = OBJECT_ID(N'PRODORDER'))
BEGIN
	ALTER TABLE PRODORDER
	ADD ORDERSTATUS VARCHAR(50) NULL
END
GO


--IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'EXPECTEDINDATE' AND [object_id] = OBJECT_ID(N'PURCHASEITEM'))
--BEGIN
--	ALTER TABLE PURCHASEITEM
--	ADD EXPECTEDINDATE DATETIME NULL
--END
--GO


IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'RECEIVEDWEIGHT' AND [object_id] = OBJECT_ID(N'INVITEM'))
BEGIN
	ALTER TABLE INVITEM
	ADD RECEIVEDWEIGHT INT NULL
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'VENDORWEIGHT' AND [object_id] = OBJECT_ID(N'INVITEM'))
BEGIN
	ALTER TABLE INVITEM
	ADD VENDORWEIGHT INT NULL
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'UNITSREMAININGVOLUME' AND [object_id] = OBJECT_ID(N'INVITEM'))
BEGIN
	ALTER TABLE INVITEM
	ADD UNITSREMAININGVOLUME INT NULL
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'UNITSREMAININGWEIGHT' AND [object_id] = OBJECT_ID(N'INVITEM'))
BEGIN
	ALTER TABLE INVITEM
	ADD UNITSREMAININGWEIGHT INT NULL
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'PH' AND [object_id] = OBJECT_ID(N'INVITEM'))
BEGIN
	ALTER TABLE INVITEM
	ADD PH DECIMAL(18,2) NULL
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'SG' AND [object_id] = OBJECT_ID(N'INVITEM'))
BEGIN
	ALTER TABLE INVITEM
	ADD SG DECIMAL(18,3) NULL
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'COLOR' AND [object_id] = OBJECT_ID(N'INVITEM'))
BEGIN
	ALTER TABLE INVITEM
	ADD COLOR VARCHAR(50) NULL
END
GO



IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'VENDORTESTINGMATRIX'))
BEGIN
CREATE TABLE [dbo].[VENDORTESTINGMATRIX](
	[VENDORTESTINGMATRIXID] [int] IDENTITY(1,1) NOT NULL,
	[VENDORID] [int] NULL,
	[CHEMICALCATEGORY] [varchar](20) NULL,
	[PRODUCTID] [int] NULL,
	[RETAINPERCENTAGE] [int] NULL,
	[TESTPERCENTAGE] [int] NULL,
	[PH] [bit] NULL,
	[SG] [bit] NULL,
	[COLOR] [bit] NULL,
	[APPEARANCE] [bit] NULL,
	[ISACTIVE] [bit] NULL,
	[CREATEDBY] [varchar](50) NULL,
	[CREATEDTIME] [datetime] NULL,
	[MODIFYBY] [varchar](50) NULL,
	[MODIFYTIME] [datetime] NULL,
 CONSTRAINT [PK_VENDORTESTINGMATRIX] PRIMARY KEY CLUSTERED 
(
	[VENDORTESTINGMATRIXID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


END
GO

IF NOT EXISTS(SELECT * FROM sys.objects WHERE   [object_id] = OBJECT_ID(N'DF_VENDORTESTINGMATRIX_PH'))
BEGIN
	ALTER TABLE [dbo].[VENDORTESTINGMATRIX] ADD  CONSTRAINT [DF_VENDORTESTINGMATRIX_PH]  DEFAULT ((0)) FOR [PH]
END
GO

IF NOT EXISTS(SELECT * FROM sys.objects WHERE   [object_id] = OBJECT_ID(N'DF_VENDORTESTINGMATRIX_PH'))
BEGIN
	ALTER TABLE [dbo].[VENDORTESTINGMATRIX] ADD  CONSTRAINT [DF_VENDORTESTINGMATRIX_PH]  DEFAULT ((0)) FOR [PH]
END
GO

IF NOT EXISTS(SELECT * FROM sys.objects WHERE   [object_id] = OBJECT_ID(N'DF_VENDORTESTINGMATRIX_SG'))
BEGIN
	ALTER TABLE [dbo].[VENDORTESTINGMATRIX] ADD  CONSTRAINT [DF_VENDORTESTINGMATRIX_SG]  DEFAULT ((0)) FOR [SG]
END
GO


IF NOT EXISTS(SELECT * FROM sys.objects WHERE   [object_id] = OBJECT_ID(N'DF_VENDORTESTINGMATRIX_COLOR'))
BEGIN
	ALTER TABLE [dbo].[VENDORTESTINGMATRIX] ADD  CONSTRAINT [DF_VENDORTESTINGMATRIX_COLOR]  DEFAULT ((0)) FOR [COLOR]
END
GO

IF NOT EXISTS(SELECT * FROM sys.objects WHERE   [object_id] = OBJECT_ID(N'DF_VENDORTESTINGMATRIX_APPEARANCE'))
BEGIN
	ALTER TABLE [dbo].[VENDORTESTINGMATRIX] ADD  CONSTRAINT [DF_VENDORTESTINGMATRIX_APPEARANCE]  DEFAULT ((0)) FOR [APPEARANCE]
END
GO

IF NOT EXISTS(SELECT * FROM sys.objects WHERE   [object_id] = OBJECT_ID(N'DF_VENDORTESTINGMATRIX_ISACTIVE'))
BEGIN
	ALTER TABLE [dbo].[VENDORTESTINGMATRIX] ADD  CONSTRAINT [DF_VENDORTESTINGMATRIX_ISACTIVE]  DEFAULT ((1)) FOR [ISACTIVE]
END
GO



--IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'NOTES' AND [object_id] = OBJECT_ID(N'PURCHASEITEM'))
--BEGIN
--	ALTER TABLE PURCHASEITEM
--	ADD NOTES VARCHAR(MAX) NULL
--END
--GO

--IF EXISTS(SELECT * FROM sys.columns WHERE [name] = N'PURCHASETYPE' AND [object_id] = OBJECT_ID(N'PURCHASEITEM'))
--BEGIN
--	ALTER TABLE PURCHASEITEM
--	ALTER COLUMN PURCHASETYPE VARCHAR(20) NULL
--END
--GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'WOEmailSender' AND [object_id] = OBJECT_ID(N'SYSPARAMETERS'))
BEGIN
	ALTER TABLE SYSPARAMETERS ADD WOEmailSender VARCHAR(100) NULL
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'WOEmailReceiver' AND [object_id] = OBJECT_ID(N'SYSPARAMETERS'))
BEGIN
	ALTER TABLE SYSPARAMETERS ADD WOEmailReceiver VARCHAR(100) NULL
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'AllowableWeightVariancePercentage' AND [object_id] = OBJECT_ID(N'SYSPARAMETERS'))
BEGIN
	ALTER TABLE SYSPARAMETERS ADD AllowableWeightVariancePercentage INT NULL
END
GO
IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'DefaultVendorTestPercentage' AND [object_id] = OBJECT_ID(N'SYSPARAMETERS'))
BEGIN
	ALTER TABLE SYSPARAMETERS ADD DefaultVendorTestPercentage INT NULL
END
GO 

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'RCVDWEIGHT' AND [object_id] = OBJECT_ID(N'INVITEM'))
BEGIN
	ALTER TABLE INVITEM ADD RCVDWEIGHT INT NULL
END
GO 


--IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'INVENTORYCLASS' AND [object_id] = OBJECT_ID(N'PURCHASEITEM'))
--BEGIN
--	ALTER TABLE PURCHASEITEM
--	ADD INVENTORYCLASS INT NULL
--END
--GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'LIST_CHEMICALCATEGORY'))
BEGIN
	CREATE TABLE [dbo].[LIST_CHEMICALCATEGORY](
	[CHEMICALCATEGORYID] [int] IDENTITY(1,1) NOT NULL,
	[CHEMICALCATEGORY] [varchar](200) NULL
) ON [PRIMARY]

END
GO

--IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'PURCHASEITEMTYPE' AND [object_id] = OBJECT_ID(N'PURCHASEITEM'))
--BEGIN	
--	EXEC SP_RENAME 'PURCHASEITEM.PURCHASETYPE', 'PURCHASEITEMTYPE' , 'COLUMN'
--END
--GO

--IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'PURCHASEITEMSTATUS' AND [object_id] = OBJECT_ID(N'PURCHASEITEM'))
--BEGIN	
--	EXEC SP_RENAME 'PURCHASEITEM.PURCHASESTATUS', 'PURCHASEITEMSTATUS' , 'COLUMN'
--END
--GO

IF EXISTS(SELECT * FROM sys.columns WHERE [name] = N'RECEIVEDWEIGHT' AND [object_id] = OBJECT_ID(N'INVITEM'))
BEGIN	
	ALTER TABLE INVITEM
	DROP COLUMN RECEIVEDWEIGHT 
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'ALLOCATEDTYPE' AND [object_id] = OBJECT_ID(N'INVITEM'))
BEGIN
	ALTER TABLE INVITEM
	ADD ALLOCATEDTYPE	VARCHAR(15) NULL 
END
GO

GO
/****** Object:  Table [dbo].[LIST_COSTMETHOD]    Script Date: 25-12-2014 15:26:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LIST_COSTMETHOD]') AND type in (N'U'))
DROP TABLE [dbo].[LIST_COSTMETHOD]
GO
/****** Object:  Table [dbo].[LIST_COSTMETHOD]    Script Date: 25-12-2014 15:26:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LIST_COSTMETHOD]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[LIST_COSTMETHOD](
	[COSTMETHODID] [int] IDENTITY(1,1) NOT NULL,
	[COSTMETHOD] [varchar](50) NULL,
 CONSTRAINT [PK_LIST_COSTMETHOD] PRIMARY KEY CLUSTERED 
(
	[COSTMETHODID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING OFF
GO


/****** Object:  Table [dbo].[WORKORDEREMAILPLAN] ******/
IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'WORKORDEREMAILPLAN'))
BEGIN
CREATE TABLE [dbo].[WORKORDEREMAILPLAN](
	[WORKORDEREMAILPLANID] [int] IDENTITY(1,1) NOT NULL,
	[TOEMAILID] [varchar](250) NULL,
	[SUBJECTTEXT] [varchar](250) NULL,
	[BODYTEXT] [varchar](max) NULL,
	[CREATEDBY] [varchar](50) NOT NULL,
	[CREATEDTIME] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WORKORDEREMAILPLANID] ASC
)
) ON [PRIMARY]
END
GO


/* Shaun's Changes January 2014 - Start*/
IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'KEEPFROMFREEZING' AND [object_id] = OBJECT_ID(N'SHIPMENT'))
BEGIN
	ALTER TABLE SHIPMENT ADD KEEPFROMFREEZING BIT DEFAULT(0)
END
/* Shaun's Changes January 2014 - End*/

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'SOURCEDOCUMENT' AND [object_id] = OBJECT_ID(N'INVPHYS'))
BEGIN
    ALTER TABLE INVPHYS ADD [SOURCEDOCUMENT] [INT] NULL
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'SOURCETYPE' AND [object_id] = OBJECT_ID(N'INVPHYS'))
BEGIN
    ALTER TABLE INVPHYS ADD [SOURCETYPE] [varchar](50) NULL
END
GO

IF EXISTS(SELECT * FROM sys.columns WHERE [name] = N'PURCHASETYPE' AND [object_id] = OBJECT_ID(N'PURCHASEITEMHISTORY'))
BEGIN
	ALTER TABLE PURCHASEITEMHISTORY
	ALTER COLUMN PURCHASETYPE VARCHAR(20) NOT NULL
END
GO

/* Shaun's Tables */
/****** Object:  Table [dbo].[RPT_SALESINVOICEDATA]    Script Date: 02/26/2015 12:49:00 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RPT_SALESINVOICEDATA]') AND type in (N'U'))
DROP TABLE [dbo].[RPT_SALESINVOICEDATA]
GO

/****** Object:  Table [dbo].[RPT_SALESINVOICEDATA]    Script Date: 02/26/2015 12:49:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RPT_SALESINVOICEDATA](
      [InvoiceNumber] [int] NOT NULL,
      [InvoiceDate] [datetime] NULL,
      [CustID] [int] NULL,
CONSTRAINT [PK_RPT_SALESINVOICEDATA] PRIMARY KEY CLUSTERED 
(
      [InvoiceNumber] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'ESTIMATEDCOMPLETIONDATE' AND [object_id] = OBJECT_ID(N'PRODORDER'))
BEGIN
	ALTER TABLE PRODORDER
	ADD ESTIMATEDCOMPLETIONDATE DATETIME
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'SETPRODORDESTCOMPDATE' AND [object_id] = OBJECT_ID(N'SYSPARAMETERS'))
BEGIN
	ALTER TABLE SYSPARAMETERS
	ADD SETPRODORDESTCOMPDATE BIT NOT NULL DEFAULT(1)
END
GO

/****** Object:  Table [dbo].[LIST_PURCHASEORDERTYPE] ******/
IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'LIST_PURCHASEORDERTYPE'))
BEGIN
CREATE TABLE [dbo].[LIST_PURCHASEORDERTYPE](
	[PURCHASEORDERTYPEID] [int] NOT NULL,
	[PURCHASEORDERTYPE] [varchar](10) NOT NULL,
	[CREATEDBY] [varchar](50) NOT NULL,
	[CREATEDTIME] [datetime] NOT NULL,
	[MODIFYBY] [varchar](50) NULL,
	[MODIFYTIME] [datetime] NULL,
 CONSTRAINT [PK_LIST_PURCHASEORDERTYPE] PRIMARY KEY CLUSTERED 
(
	[PURCHASEORDERTYPEID] 
)) 
END
GO

--ALTER TABLE PURCHASEITEM
--ALTER COLUMN DATENEEDED DATETIME NULL

GO

/*********************************** Relabel **********************************/


IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'RELABELORDER'))
BEGIN
CREATE TABLE [dbo].[RELABELORDER](
	[RELABELORDERNUMBER] [int] IDENTITY(1,1) NOT NULL,
	[RELABELORDERDATE] [datetime] NULL,
	[QTY] [int] NULL,
	[CUSTID] [int] NULL,
	[NEEDEDBY] [datetime] NULL,
	[ITEMID] [int] NULL,
	[WORKORDERNUMBER] [int] NULL,
	[RELABELORDERSTATUS] [varchar](50) NULL,
	[CREATEDBY] [varchar](50) NULL,
	[CREATEDTIME] [datetime] NULL,
	[MODIFYBY] [varchar](50) NULL,
	[MODIFYTIME] [datetime] NULL,
 CONSTRAINT [PK_RELABELORDER] PRIMARY KEY CLUSTERED 
(
	[RELABELORDERNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


END
GO




IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'RELABELORDERITEM'))
BEGIN
CREATE TABLE [dbo].[RELABELORDERITEM](
	[RELABELORDERITEMNUMBER] [int] IDENTITY(1,1) NOT NULL,
	[RELABELORDERNUMBER] [int] NOT NULL,
	[ITEMID] [int] NULL,
	[INVITEMNUM] [int] NULL,
	[WORKORDERITEMNUMBER] [int] NULL,
	[SOURCETYPE] [varchar](50) NULL,
	[SOURCEDOC] [int] NULL,
	[RELABELORDERITEMSTATUS] [varchar](50) NULL,
	[CREATEDBY] [varchar](50) NULL,
	[CREATEDTIME] [datetime] NULL,
	[MODIFYBY] [varchar](50) NULL,
	[MODIFYTIME] [datetime] NULL,
 CONSTRAINT [PK_RELABELORDERITEM] PRIMARY KEY CLUSTERED 
(
	[RELABELORDERITEMNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO


IF EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'PURCHASEITEM'))
BEGIN
	DROP TABLE PURCHASEITEM
END
GO


/****** Object:  Table [dbo].[PURCHASEITEM] ******/
IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'PURCHASEITEM'))
BEGIN
CREATE TABLE [dbo].[PURCHASEITEM](
	[PURCHASEITEMID] [int] IDENTITY(1,1) NOT NULL,
	[PURCHASEITEMTYPE] [varchar](20) NULL,
	[ITEMID] [int] NOT NULL,
	[ITEMTYPE] [varchar](50) NOT NULL,
	[ITEMDESCRIPTION] [varchar](200) NULL,
	[QTY] [numeric](18, 4) NOT NULL,
	[UNITORCONTAINER] [varchar](1) NOT NULL,
	[CONTAINER] [varchar](50) NULL,
	[UNITSINCONTAINER] [int] NULL,
	[UOM] [varchar](8) NULL,
	[UNITCOST] [decimal](18, 4) NULL,
	[DATENEEDED] [datetime] NULL,
	[VENDORID] [int] NULL,
	[CUSTOMERID] [int] NULL,
	[PURCHASENUMBER] [int] NULL,
	[PURCHASEITEMSTATUS] VARCHAR(50) NULL,
	[SOURCETYPE] VARCHAR(50) NULL,
	[SOURCEDOCUMENT] INTEGER NULL,
	[EXPECTEDINDATE] [datetime] NULL,
	[NOTES] VARCHAR(MAX) NULL,
	[INVENTORYCLASS] INT NULL,
	[VENDORITEMNUMBER] [varchar](50) NULL,
	[CUSTOMERPO] [varchar](50) NULL,
	[CREATEDBY] [varchar](50) NOT NULL,
	[CREATEDTIME] [datetime] NOT NULL,
	[MODIFYBY] [varchar](50) NULL,
	[MODIFYTIME] [datetime] NULL,
 CONSTRAINT [PK_PURCHASEITM] PRIMARY KEY CLUSTERED 
(
	[PURCHASEITEMID] ASC
))
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'RELABELINSTRUCTION'))
BEGIN
CREATE TABLE [dbo].[RELABELINSTRUCTION](
	[RELABELINSTRUCTIONNUMBER] [int] IDENTITY(1,1) NOT NULL,
	[SEQUENCE] [int] NULL,
	[RELABELINSTRUCTION] [varchar](max) NULL,
 CONSTRAINT [PK_RELABELINSTRUCTION] PRIMARY KEY CLUSTERED 
(
	[RELABELINSTRUCTIONNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

END
GO


IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'PRODUCTRELABELINSTRUCTION'))
BEGIN
CREATE TABLE [dbo].[PRODUCTRELABELINSTRUCTION](
	[PRODUCTRELABELINSTRUCTIONNUMBER] [int] IDENTITY(1,1) NOT NULL,
	[SEQUENCE] [int] NULL,
	[RELABELINSTRUCTION] [varchar](max) NULL,
	[FULFILLMENTPLANID] [int] NULL,    
	[CREATEDBY] [varchar](50) NULL,    
	[CREATEDTIME] [datetime] NULL,
	[MODIFYBY] [varchar](50) NULL,
	[MODIFYTIME] [datetime] NULL,
 CONSTRAINT [PK_PRODUCTRELABELINSTRUCTION] PRIMARY KEY CLUSTERED 
(
	[PRODUCTRELABELINSTRUCTIONNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

END
GO

/* Shaun's changes from 14.47 - 04/27/2015 1:30 PM */

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'LABELTYPE' AND [object_id] = OBJECT_ID(N'PRODUCT'))
BEGIN
	ALTER TABLE PRODUCT
	ADD LABELTYPE VARCHAR(50)
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'LABELDEFAULTQTY' AND [object_id] = OBJECT_ID(N'PRODUCT'))
BEGIN
	ALTER TABLE PRODUCT
	ADD LABELDEFAULTQTY INT
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'CHEMICALCOLOR' AND [object_id] = OBJECT_ID(N'PRODUCT'))
BEGIN
	ALTER TABLE PRODUCT
	ADD CHEMICALCOLOR VARCHAR(50)
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'CHEMICALCLARITY' AND [object_id] = OBJECT_ID(N'PRODUCT'))
BEGIN
	ALTER TABLE PRODUCT
	ADD CHEMICALCLARITY VARCHAR(50)
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'CLARITY' AND [object_id] = OBJECT_ID(N'TESTSAMPLE'))
BEGIN
	ALTER TABLE TESTSAMPLE
	ADD CLARITY VARCHAR(50)
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'LIST_CHEMICALCOLOR'))
BEGIN
	CREATE TABLE [dbo].[LIST_CHEMICALCOLOR](
		[COLOR] [varchar](50) NOT NULL,
	 CONSTRAINT [PK_LIST_CHEMICALCOLOR] PRIMARY KEY CLUSTERED 
	(
		[COLOR] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N'LIST_CHEMICALCLARITY'))
BEGIN
	CREATE TABLE [dbo].[LIST_CHEMICALCLARITY](
		[CLARITY] [varchar](50) NOT NULL,
	 CONSTRAINT [PK_LIST_CHEMICALCLARITY] PRIMARY KEY CLUSTERED 
	(
		[CLARITY] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE [name] = N'ADDITIONALDEFAULTSENDTOADDRESS' AND [object_id] = OBJECT_ID(N'SYSPARAMETERS'))
BEGIN
	ALTER TABLE SYSPARAMETERS
	ADD ADDITIONALDEFAULTSENDTOADDRESS VARCHAR(100)
END
GO