
USE AOSTEST

/***************************************** RELEASE 14.50 *****************************************************************/
IF NOT EXISTS (SELECT * FROM [LIST_FULFILLMENTTYPE])
BEGIN
	--SET IDENTITY_INSERT [dbo].[LIST_FULFILLMENTTYPE] ON
	
	INSERT INTO [dbo].[LIST_FULFILLMENTTYPE](FULFILLMENTTYPEID, [FULFILLMENTTYPE], [DESCRIPTION], [CREATEDBY], [CREATEDTIME], [MODIFYBY], [MODIFYTIME])
		 VALUES(1, 'INV','INVENTORY', 'SYSTEM', GETDATE(), NULL, NULL)

	INSERT INTO [dbo].[LIST_FULFILLMENTTYPE](FULFILLMENTTYPEID, [FULFILLMENTTYPE], [DESCRIPTION], [CREATEDBY], [CREATEDTIME], [MODIFYBY], [MODIFYTIME])
		 VALUES(2, 'RLBL','RELABEL', 'SYSTEM', GETDATE(), NULL, NULL)

	INSERT INTO [dbo].[LIST_FULFILLMENTTYPE](FULFILLMENTTYPEID, [FULFILLMENTTYPE], [DESCRIPTION], [CREATEDBY], [CREATEDTIME], [MODIFYBY], [MODIFYTIME])
		 VALUES(3, 'CONV','CONVERSION', 'SYSTEM', GETDATE(), NULL, NULL)

	INSERT INTO [dbo].[LIST_FULFILLMENTTYPE](FULFILLMENTTYPEID, [FULFILLMENTTYPE], [DESCRIPTION], [CREATEDBY], [CREATEDTIME], [MODIFYBY], [MODIFYTIME])
		 VALUES(4, 'PORD','PRODUCTION ORDER', 'SYSTEM', GETDATE(), NULL, NULL)

	INSERT INTO [dbo].[LIST_FULFILLMENTTYPE](FULFILLMENTTYPEID, [FULFILLMENTTYPE], [DESCRIPTION], [CREATEDBY], [CREATEDTIME], [MODIFYBY], [MODIFYTIME])
		 VALUES(5, 'PRCH','PURCHASE', 'SYSTEM', GETDATE(), NULL, NULL)

END
GO

/************************* INSERT SCRIPT FOR PRODUCTFULFILLMENTPLAN  *************************/
IF NOT EXISTS (SELECT * FROM PRODUCTFULFILLMENTPLAN WHERE FULFILLMENTTYPEID = 1 AND PRODUCTID IS NULL)
BEGIN
	INSERT INTO PRODUCTFULFILLMENTPLAN VALUES (NULL, 1, 1, NULL, 'SYSTEM', GETDATE(), NULL, NULL)
END
IF NOT EXISTS (SELECT * FROM PRODUCTFULFILLMENTPLAN WHERE FULFILLMENTTYPEID = 4 AND PRODUCTID IS NULL)
BEGIN
	INSERT INTO PRODUCTFULFILLMENTPLAN VALUES (NULL, 4, 2, NULL, 'SYSTEM', GETDATE(), NULL, NULL)
END
IF NOT EXISTS (SELECT * FROM PRODUCTFULFILLMENTPLAN WHERE FULFILLMENTTYPEID = 5 AND PRODUCTID IS NULL)
BEGIN
	INSERT INTO PRODUCTFULFILLMENTPLAN VALUES (NULL, 5, 3, NULL, 'SYSTEM', GETDATE(), NULL, NULL)
END

/************************* INSERT SCRIPT FOR PRODUCTFULFILLMENTPLAN  *************************/
IF NOT EXISTS (SELECT * FROM [LIST_COSTTYPE] WHERE [COSTTYPE] = 'REGULAR')
BEGIN
	INSERT [dbo].[LIST_COSTTYPE] ([RecID], [COSTTYPE]) VALUES (1, N'REGULAR')
END
GO
IF NOT EXISTS (SELECT * FROM [LIST_COSTTYPE] WHERE [COSTTYPE] = 'DIRECT')
BEGIN
	INSERT [dbo].[LIST_COSTTYPE] ([RecID], [COSTTYPE]) VALUES (2, N'DIRECT')
END
GO

--------------14.504 Release ----------------

UPDATE [dbo].[SYSPARAMETERS] SET WOEmailSender = 'Orders@americoChemical.com', WOEmailReceiver = 'aarshi@alligatortek.com' WHERE WOEmailSender IS NULL
UPDATE SYSPARAMETERS SET ALLOWABLEWEIGHTVARIANCEPERCENTAGE = 1 WHERE ALLOWABLEWEIGHTVARIANCEPERCENTAGE IS NULL
UPDATE SYSPARAMETERS SET DEFAULTVENDORTESTPERCENTAGE = 100 WHERE DEFAULTVENDORTESTPERCENTAGE IS NULL

GO

IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCATEGORY] WHERE CHEMICALCATEGORY = 'BLENDS')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCATEGORY]
           ([CHEMICALCATEGORY])
     VALUES
           ('BLENDS')
END

GO

IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCATEGORY] WHERE CHEMICALCATEGORY = 'COMMODITIES')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCATEGORY]
           ([CHEMICALCATEGORY])
     VALUES
           ('COMMODITIES')
END

IF NOT EXISTS(SELECT COSTMETHOD FROM [LIST_COSTMETHOD] WHERE COSTMETHOD ='VOLUME')
BEGIN
	INSERT INTO [dbo].[LIST_COSTMETHOD]
           ([COSTMETHOD])
     VALUES
           ('VOLUME')
END

IF NOT EXISTS(SELECT COSTMETHOD FROM [LIST_COSTMETHOD] WHERE COSTMETHOD ='WEIGHT')
BEGIN
	INSERT INTO [dbo].[LIST_COSTMETHOD]
           ([COSTMETHOD])
     VALUES
           ('WEIGHT')
END

IF NOT EXISTS(SELECT COSTMETHOD FROM [LIST_COSTMETHOD] WHERE COSTMETHOD ='SINGLE UNIT')
BEGIN
	INSERT INTO [dbo].[LIST_COSTMETHOD]
           ([COSTMETHOD])
     VALUES
           ('SINGLE UNIT')
END

IF EXISTS (SELECT 1 FROM MATERIALPRODUCT WHERE [priority] IS NULL)
BEGIN
	UPDATE MATERIALPRODUCT SET PRIORITY = 1 WHERE [PRIORITY] IS NULL
END

IF NOT EXISTS (SELECT 1 FROM LIST_PALLETTYPE WHERE PALLETTYPE = 'FULL-PLASTIC')
BEGIN
	INSERT INTO LIST_PALLETTYPE VALUES ('FULL-PLASTIC', 60)
END

IF NOT EXISTS (SELECT 1 FROM LIST_PALLETTYPE WHERE PALLETTYPE = 'FULL-WOOD')
BEGIN
	INSERT INTO LIST_PALLETTYPE VALUES ('FULL-WOOD', 60)
END

IF NOT EXISTS (SELECT 1 FROM LIST_PALLETTYPE WHERE PALLETTYPE = 'HALF-PLASTIC')
BEGIN
	INSERT INTO LIST_PALLETTYPE VALUES ('HALF-PLASTIC', 60)
END

IF NOT EXISTS (SELECT 1 FROM LIST_PALLETTYPE WHERE PALLETTYPE = 'HALF-WOOD')
BEGIN
	INSERT INTO LIST_PALLETTYPE VALUES ('HALF-WOOD', 60)
END

IF NOT EXISTS (SELECT 1 FROM [LIST_INVITEMSTATUS] WHERE LOOKUPGROUP = 'InvItemStatus' AND LOOKUPDESC = 'PENDING')
BEGIN
	INSERT INTO [LIST_INVITEMSTATUS] VALUES ('InvItemStatus', 15, 'PENDING')
END

IF NOT EXISTS (SELECT 1 FROM [LIST_INVITEMSTATUS] WHERE LOOKUPGROUP = 'InvItemStatus' AND LOOKUPDESC = 'INPROD')
BEGIN
	INSERT INTO [LIST_INVITEMSTATUS] VALUES ('InvItemStatus', 16, 'INPROD')
END

IF NOT EXISTS (SELECT 1 FROM [LIST_INVITEMSTATUS] WHERE LOOKUPGROUP = 'InvItemStatus' AND LOOKUPDESC = 'FORRLBL')
BEGIN
	INSERT INTO [LIST_INVITEMSTATUS] VALUES ('InvItemStatus', 17, 'FORRLBL')
END

IF NOT EXISTS (SELECT 1 FROM [LIST_INVITEMSTATUS] WHERE LOOKUPGROUP = 'InvItemStatus' AND LOOKUPDESC = 'RELABELED')
BEGIN
	INSERT INTO [LIST_INVITEMSTATUS] VALUES ('InvItemStatus', 18, 'RELABELED')
END

IF NOT EXISTS (SELECT 1 FROM [LIST_INVITEMSTATUS] WHERE LOOKUPGROUP = 'InvItemStatus' AND LOOKUPDESC = 'VENDOR')
BEGIN
	INSERT INTO [LIST_INVITEMSTATUS] VALUES ('InvItemStatus', 19, 'VENDOR')
END
GO

IF NOT EXISTS (SELECT 1 FROM [LIST_INVITEMSTATUS] WHERE LOOKUPGROUP = 'InvItemStatus' AND LOOKUPDESC = 'RCVDHOLD')
BEGIN
	INSERT INTO [LIST_INVITEMSTATUS] VALUES ('InvItemStatus', 20, 'RCVDHOLD')
END
GO


IF NOT EXISTS (SELECT * FROM [LIST_PURCHASEORDERTYPE] WHERE [PURCHASEORDERTYPE] = 'DIRECT')
BEGIN
	INSERT INTO [dbo].[LIST_PURCHASEORDERTYPE](PURCHASEORDERTYPEID, [PURCHASEORDERTYPE], [CREATEDBY], [CREATEDTIME], [MODIFYBY], [MODIFYTIME])
		 VALUES(1, 'DIRECT', 'SYSTEM', GETDATE(), NULL, NULL)
END
GO

IF NOT EXISTS (SELECT * FROM [LIST_PURCHASEORDERTYPE] WHERE [PURCHASEORDERTYPE] = 'REGULAR')
BEGIN
	INSERT INTO [dbo].[LIST_PURCHASEORDERTYPE](PURCHASEORDERTYPEID, [PURCHASEORDERTYPE], [CREATEDBY], [CREATEDTIME], [MODIFYBY], [MODIFYTIME])
		 VALUES(2, 'REGULAR', 'SYSTEM', GETDATE(), NULL, NULL)
END
GO

/*********************************** Relabel **********************************/

UPDATE INVITEM SET ALLOCATEDTYPE = 'WORKORDER' WHERE ALLOCATEDDOCUMENT IS NOT NULL AND ALLOCATEDTYPE IS NULL
GO

IF NOT EXISTS (SELECT * FROM RELABELINSTRUCTION)
BEGIN
	INSERT [dbo].[RELABELINSTRUCTION] ([SEQUENCE], [RELABELINSTRUCTION]) 
	VALUES (1, 'Relabel Instruction 1'),
		(2, 'Relabel Instruction 2'),
		(3, 'Relabel Instruction 3'),
		(4, 'Relabel Instruction 4'),
		(5, 'Relabel Instruction 5'),
		(6, 'Relabel Instruction 6'),
		(7, 'Relabel Instruction 7'),
		(8, 'Relabel Instruction 8'),
		(9, 'Relabel Instruction 9'),
		(10, 'Relabel Instruction 10')

END
GO

IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCLARITY] WHERE CLARITY = 'CLEAR')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCLARITY]
           ([CLARITY])
     VALUES
           ('CLEAR')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCLARITY] WHERE CLARITY = 'CLOUDY')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCLARITY]
           ([CLARITY])
     VALUES
           ('CLOUDY')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCLARITY] WHERE CLARITY = 'HAZY')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCLARITY]
           ([CLARITY])
     VALUES
           ('HAZY')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCLARITY] WHERE CLARITY = 'SLIGHTLY HAZY')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCLARITY]
           ([CLARITY])
     VALUES
           ('SLIGHTLY HAZY')
END

IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCOLOR] WHERE [COLOR] = 'BLUE')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCOLOR]
           ([COLOR])
     VALUES
           ('BLUE')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCOLOR] WHERE [COLOR] = 'BROWN')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCOLOR]
           ([COLOR])
     VALUES
           ('BROWN')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCOLOR] WHERE [COLOR] = 'COLORLESS')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCOLOR]
           ([COLOR])
     VALUES
           ('COLORLESS')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCOLOR] WHERE [COLOR] = 'DARK BROWN')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCOLOR]
           ([COLOR])
     VALUES
           ('DARK BROWN')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCOLOR] WHERE [COLOR] = 'DARK GREEN')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCOLOR]
           ([COLOR])
     VALUES
           ('DARK GREEN')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCOLOR] WHERE [COLOR] = 'GREEN')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCOLOR]
           ([COLOR])
     VALUES
           ('GREEN')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCOLOR] WHERE [COLOR] = 'LIGHT GREEN')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCOLOR]
           ([COLOR])
     VALUES
           ('LIGHT GREEN')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCOLOR] WHERE [COLOR] = 'PURPLE')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCOLOR]
           ([COLOR])
     VALUES
           ('PURPLE')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCOLOR] WHERE [COLOR] = 'RED')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCOLOR]
           ([COLOR])
     VALUES
           ('RED')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCOLOR] WHERE [COLOR] = 'SLIGHT YELLOW TINT')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCOLOR]
           ([COLOR])
     VALUES
           ('SLIGHT YELLOW TINT')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCOLOR] WHERE [COLOR] = 'WHITE')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCOLOR]
           ([COLOR])
     VALUES
           ('WHITE')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCOLOR] WHERE [COLOR] = 'WHITE TINT')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCOLOR]
           ([COLOR])
     VALUES
           ('WHITE TINT')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCOLOR] WHERE [COLOR] = 'YELLOW')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCOLOR]
           ([COLOR])
     VALUES
           ('YELLOW')
END
IF NOT EXISTS (SELECT * FROM [LIST_CHEMICALCOLOR] WHERE [COLOR] = 'YELLOW TINT')
BEGIN
INSERT INTO [dbo].[LIST_CHEMICALCOLOR]
           ([COLOR])
     VALUES
           ('YELLOW TINT')
END

IF EXISTS (SELECT 1 FROM SYSPARAMETERS)
BEGIN
	UPDATE SYSPARAMETERS
	SET COMPANYEMAILDOMAIN = 'americoChemical.com', COMPANYEMAILSERVER = '192.168.1.50', ADDITIONALDEFAULTSENDTOADDRESS = 'orders@americochemical.com'
	WHERE RecordID = 1
END


