'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace ProductionOrder
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ProductionOrderSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ProductionOrder
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetProdItemsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetProdItemDetailsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetInvItemDetailsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProdItemAddTransactionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProdItemMoveOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateProdOrderTimerOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PrintLabelL1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private PrintLabelL1FromAOSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.AOS.My.MySettings.Default.AOS_ProductionOrder_ProductionOrder
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetProdItemsCompleted As GetProdItemsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetProdItemDetailsCompleted As GetProdItemDetailsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetInvItemDetailsCompleted As GetInvItemDetailsCompletedEventHandler
        
        '''<remarks/>
        Public Event ProdItemAddTransactionCompleted As ProdItemAddTransactionCompletedEventHandler
        
        '''<remarks/>
        Public Event ProdItemMoveCompleted As ProdItemMoveCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateProdOrderTimerCompleted As UpdateProdOrderTimerCompletedEventHandler
        
        '''<remarks/>
        Public Event PrintLabelL1Completed As PrintLabelL1CompletedEventHandler
        
        '''<remarks/>
        Public Event PrintLabelL1FromAOSCompleted As PrintLabelL1FromAOSCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProdItems", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProdItems(ByVal productionOrderNo As Integer, ByVal sessionID As String) As ResponseBE
            Dim results() As Object = Me.Invoke("GetProdItems", New Object() {productionOrderNo, sessionID})
            Return CType(results(0),ResponseBE)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetProdItemsAsync(ByVal productionOrderNo As Integer, ByVal sessionID As String)
            Me.GetProdItemsAsync(productionOrderNo, sessionID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetProdItemsAsync(ByVal productionOrderNo As Integer, ByVal sessionID As String, ByVal userState As Object)
            If (Me.GetProdItemsOperationCompleted Is Nothing) Then
                Me.GetProdItemsOperationCompleted = AddressOf Me.OnGetProdItemsOperationCompleted
            End If
            Me.InvokeAsync("GetProdItems", New Object() {productionOrderNo, sessionID}, Me.GetProdItemsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetProdItemsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetProdItemsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetProdItemsCompleted(Me, New GetProdItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProdItemDetails", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProdItemDetails(ByVal prodItemNo As Integer, ByVal sessionID As String) As ProdItemBE
            Dim results() As Object = Me.Invoke("GetProdItemDetails", New Object() {prodItemNo, sessionID})
            Return CType(results(0),ProdItemBE)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetProdItemDetailsAsync(ByVal prodItemNo As Integer, ByVal sessionID As String)
            Me.GetProdItemDetailsAsync(prodItemNo, sessionID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetProdItemDetailsAsync(ByVal prodItemNo As Integer, ByVal sessionID As String, ByVal userState As Object)
            If (Me.GetProdItemDetailsOperationCompleted Is Nothing) Then
                Me.GetProdItemDetailsOperationCompleted = AddressOf Me.OnGetProdItemDetailsOperationCompleted
            End If
            Me.InvokeAsync("GetProdItemDetails", New Object() {prodItemNo, sessionID}, Me.GetProdItemDetailsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetProdItemDetailsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetProdItemDetailsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetProdItemDetailsCompleted(Me, New GetProdItemDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInvItemDetails", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetInvItemDetails(ByVal invNumber As Integer, ByVal prodItemNo As Integer, ByVal sessionID As String) As InvItemBE
            Dim results() As Object = Me.Invoke("GetInvItemDetails", New Object() {invNumber, prodItemNo, sessionID})
            Return CType(results(0),InvItemBE)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetInvItemDetailsAsync(ByVal invNumber As Integer, ByVal prodItemNo As Integer, ByVal sessionID As String)
            Me.GetInvItemDetailsAsync(invNumber, prodItemNo, sessionID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetInvItemDetailsAsync(ByVal invNumber As Integer, ByVal prodItemNo As Integer, ByVal sessionID As String, ByVal userState As Object)
            If (Me.GetInvItemDetailsOperationCompleted Is Nothing) Then
                Me.GetInvItemDetailsOperationCompleted = AddressOf Me.OnGetInvItemDetailsOperationCompleted
            End If
            Me.InvokeAsync("GetInvItemDetails", New Object() {invNumber, prodItemNo, sessionID}, Me.GetInvItemDetailsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetInvItemDetailsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetInvItemDetailsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetInvItemDetailsCompleted(Me, New GetInvItemDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProdItemAddTransaction", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProdItemAddTransaction(ByVal itemNumber As Integer, ByVal prodItemNum As Integer, ByVal type As String, ByVal units As Double, ByVal sessionID As String) As ResponseBE
            Dim results() As Object = Me.Invoke("ProdItemAddTransaction", New Object() {itemNumber, prodItemNum, type, units, sessionID})
            Return CType(results(0),ResponseBE)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProdItemAddTransactionAsync(ByVal itemNumber As Integer, ByVal prodItemNum As Integer, ByVal type As String, ByVal units As Double, ByVal sessionID As String)
            Me.ProdItemAddTransactionAsync(itemNumber, prodItemNum, type, units, sessionID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProdItemAddTransactionAsync(ByVal itemNumber As Integer, ByVal prodItemNum As Integer, ByVal type As String, ByVal units As Double, ByVal sessionID As String, ByVal userState As Object)
            If (Me.ProdItemAddTransactionOperationCompleted Is Nothing) Then
                Me.ProdItemAddTransactionOperationCompleted = AddressOf Me.OnProdItemAddTransactionOperationCompleted
            End If
            Me.InvokeAsync("ProdItemAddTransaction", New Object() {itemNumber, prodItemNum, type, units, sessionID}, Me.ProdItemAddTransactionOperationCompleted, userState)
        End Sub
        
        Private Sub OnProdItemAddTransactionOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProdItemAddTransactionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProdItemAddTransactionCompleted(Me, New ProdItemAddTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProdItemMove", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProdItemMove(ByVal prodItemNum As Integer, ByVal warehouselocation As String, ByVal sessionID As String) As ResponseBE
            Dim results() As Object = Me.Invoke("ProdItemMove", New Object() {prodItemNum, warehouselocation, sessionID})
            Return CType(results(0),ResponseBE)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProdItemMoveAsync(ByVal prodItemNum As Integer, ByVal warehouselocation As String, ByVal sessionID As String)
            Me.ProdItemMoveAsync(prodItemNum, warehouselocation, sessionID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProdItemMoveAsync(ByVal prodItemNum As Integer, ByVal warehouselocation As String, ByVal sessionID As String, ByVal userState As Object)
            If (Me.ProdItemMoveOperationCompleted Is Nothing) Then
                Me.ProdItemMoveOperationCompleted = AddressOf Me.OnProdItemMoveOperationCompleted
            End If
            Me.InvokeAsync("ProdItemMove", New Object() {prodItemNum, warehouselocation, sessionID}, Me.ProdItemMoveOperationCompleted, userState)
        End Sub
        
        Private Sub OnProdItemMoveOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProdItemMoveCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProdItemMoveCompleted(Me, New ProdItemMoveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateProdOrderTimer", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateProdOrderTimer(ByVal prodOrderNo As Integer, ByVal action As String, ByVal sessionID As String) As ResponseBE
            Dim results() As Object = Me.Invoke("UpdateProdOrderTimer", New Object() {prodOrderNo, action, sessionID})
            Return CType(results(0),ResponseBE)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateProdOrderTimerAsync(ByVal prodOrderNo As Integer, ByVal action As String, ByVal sessionID As String)
            Me.UpdateProdOrderTimerAsync(prodOrderNo, action, sessionID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateProdOrderTimerAsync(ByVal prodOrderNo As Integer, ByVal action As String, ByVal sessionID As String, ByVal userState As Object)
            If (Me.UpdateProdOrderTimerOperationCompleted Is Nothing) Then
                Me.UpdateProdOrderTimerOperationCompleted = AddressOf Me.OnUpdateProdOrderTimerOperationCompleted
            End If
            Me.InvokeAsync("UpdateProdOrderTimer", New Object() {prodOrderNo, action, sessionID}, Me.UpdateProdOrderTimerOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateProdOrderTimerOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateProdOrderTimerCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateProdOrderTimerCompleted(Me, New UpdateProdOrderTimerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrintLabelL1", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PrintLabelL1(ByVal invItemNumber As Integer, ByVal sessionID As String) As ResponseBE
            Dim results() As Object = Me.Invoke("PrintLabelL1", New Object() {invItemNumber, sessionID})
            Return CType(results(0),ResponseBE)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PrintLabelL1Async(ByVal invItemNumber As Integer, ByVal sessionID As String)
            Me.PrintLabelL1Async(invItemNumber, sessionID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PrintLabelL1Async(ByVal invItemNumber As Integer, ByVal sessionID As String, ByVal userState As Object)
            If (Me.PrintLabelL1OperationCompleted Is Nothing) Then
                Me.PrintLabelL1OperationCompleted = AddressOf Me.OnPrintLabelL1OperationCompleted
            End If
            Me.InvokeAsync("PrintLabelL1", New Object() {invItemNumber, sessionID}, Me.PrintLabelL1OperationCompleted, userState)
        End Sub
        
        Private Sub OnPrintLabelL1OperationCompleted(ByVal arg As Object)
            If (Not (Me.PrintLabelL1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PrintLabelL1Completed(Me, New PrintLabelL1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrintLabelL1FromAOS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PrintLabelL1FromAOS(ByVal invItemNumber As Integer) As ResponseBE
            Dim results() As Object = Me.Invoke("PrintLabelL1FromAOS", New Object() {invItemNumber})
            Return CType(results(0),ResponseBE)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PrintLabelL1FromAOSAsync(ByVal invItemNumber As Integer)
            Me.PrintLabelL1FromAOSAsync(invItemNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PrintLabelL1FromAOSAsync(ByVal invItemNumber As Integer, ByVal userState As Object)
            If (Me.PrintLabelL1FromAOSOperationCompleted Is Nothing) Then
                Me.PrintLabelL1FromAOSOperationCompleted = AddressOf Me.OnPrintLabelL1FromAOSOperationCompleted
            End If
            Me.InvokeAsync("PrintLabelL1FromAOS", New Object() {invItemNumber}, Me.PrintLabelL1FromAOSOperationCompleted, userState)
        End Sub
        
        Private Sub OnPrintLabelL1FromAOSOperationCompleted(ByVal arg As Object)
            If (Not (Me.PrintLabelL1FromAOSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PrintLabelL1FromAOSCompleted(Me, New PrintLabelL1FromAOSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ResponseBE
        
        Private statusCodeField As Integer
        
        Private errorMsgField As String
        
        Private resultDataTableField As System.Data.DataTable
        
        '''<remarks/>
        Public Property StatusCode() As Integer
            Get
                Return Me.statusCodeField
            End Get
            Set
                Me.statusCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorMsg() As String
            Get
                Return Me.errorMsgField
            End Get
            Set
                Me.errorMsgField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResultDataTable() As System.Data.DataTable
            Get
                Return Me.resultDataTableField
            End Get
            Set
                Me.resultDataTableField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ContainerBE
        
        Private containerField As String
        
        Private uOMField As String
        
        Private unitsField As Integer
        
        Private tareWeightField As Integer
        
        '''<remarks/>
        Public Property Container() As String
            Get
                Return Me.containerField
            End Get
            Set
                Me.containerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UOM() As String
            Get
                Return Me.uOMField
            End Get
            Set
                Me.uOMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Units() As Integer
            Get
                Return Me.unitsField
            End Get
            Set
                Me.unitsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TareWeight() As Integer
            Get
                Return Me.tareWeightField
            End Get
            Set
                Me.tareWeightField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class InvItemBE
        
        Private containerField As ContainerBE
        
        Private responseStatusField As ResponseBE
        
        Private itemNumberField As Long
        
        Private productIDField As Long
        
        Private productField As ProductBE
        
        Private shipmentnumberField As Long
        
        Private productDescField As String
        
        Private warehouseLocationField As String
        
        Private lotNumberField As String
        
        Private receivedDateField As String
        
        Private itemStatusField As String
        
        Private allocatedDocumentField As String
        
        Private allocatedDateField As String
        
        Private shippedDateField As String
        
        Private unitsRemainingField As Decimal
        
        '''<remarks/>
        Public Property Container() As ContainerBE
            Get
                Return Me.containerField
            End Get
            Set
                Me.containerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponseStatus() As ResponseBE
            Get
                Return Me.responseStatusField
            End Get
            Set
                Me.responseStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ItemNumber() As Long
            Get
                Return Me.itemNumberField
            End Get
            Set
                Me.itemNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProductID() As Long
            Get
                Return Me.productIDField
            End Get
            Set
                Me.productIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Product() As ProductBE
            Get
                Return Me.productField
            End Get
            Set
                Me.productField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shipmentnumber() As Long
            Get
                Return Me.shipmentnumberField
            End Get
            Set
                Me.shipmentnumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProductDesc() As String
            Get
                Return Me.productDescField
            End Get
            Set
                Me.productDescField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WarehouseLocation() As String
            Get
                Return Me.warehouseLocationField
            End Get
            Set
                Me.warehouseLocationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LotNumber() As String
            Get
                Return Me.lotNumberField
            End Get
            Set
                Me.lotNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReceivedDate() As String
            Get
                Return Me.receivedDateField
            End Get
            Set
                Me.receivedDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ItemStatus() As String
            Get
                Return Me.itemStatusField
            End Get
            Set
                Me.itemStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AllocatedDocument() As String
            Get
                Return Me.allocatedDocumentField
            End Get
            Set
                Me.allocatedDocumentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AllocatedDate() As String
            Get
                Return Me.allocatedDateField
            End Get
            Set
                Me.allocatedDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShippedDate() As String
            Get
                Return Me.shippedDateField
            End Get
            Set
                Me.shippedDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UnitsRemaining() As Decimal
            Get
                Return Me.unitsRemainingField
            End Get
            Set
                Me.unitsRemainingField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ProductBE
        
        Private productIDField As Integer
        
        Private productDescriptionField As String
        
        Private uOMField As String
        
        Private unitsField As Integer
        
        Private responseStatusField As ResponseBE
        
        '''<remarks/>
        Public Property ProductID() As Integer
            Get
                Return Me.productIDField
            End Get
            Set
                Me.productIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProductDescription() As String
            Get
                Return Me.productDescriptionField
            End Get
            Set
                Me.productDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UOM() As String
            Get
                Return Me.uOMField
            End Get
            Set
                Me.uOMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Units() As Integer
            Get
                Return Me.unitsField
            End Get
            Set
                Me.unitsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponseStatus() As ResponseBE
            Get
                Return Me.responseStatusField
            End Get
            Set
                Me.responseStatusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ProdOrderBE
        
        Private pONumberField As Long
        
        Private pODateField As String
        
        Private createdByField As String
        
        Private productIdField As Integer
        
        Private productQtyField As Integer
        
        Private aPISNumberField As Integer
        
        Private custIDField As Integer
        
        Private lotNumberField As String
        
        Private neededByField As String
        
        Private isCompleteField As Boolean
        
        '''<remarks/>
        Public Property PONumber() As Long
            Get
                Return Me.pONumberField
            End Get
            Set
                Me.pONumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PODate() As String
            Get
                Return Me.pODateField
            End Get
            Set
                Me.pODateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedBy() As String
            Get
                Return Me.createdByField
            End Get
            Set
                Me.createdByField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProductId() As Integer
            Get
                Return Me.productIdField
            End Get
            Set
                Me.productIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProductQty() As Integer
            Get
                Return Me.productQtyField
            End Get
            Set
                Me.productQtyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property APISNumber() As Integer
            Get
                Return Me.aPISNumberField
            End Get
            Set
                Me.aPISNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustID() As Integer
            Get
                Return Me.custIDField
            End Get
            Set
                Me.custIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LotNumber() As String
            Get
                Return Me.lotNumberField
            End Get
            Set
                Me.lotNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NeededBy() As String
            Get
                Return Me.neededByField
            End Get
            Set
                Me.neededByField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsComplete() As Boolean
            Get
                Return Me.isCompleteField
            End Get
            Set
                Me.isCompleteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class MaterialBE
        
        Private materialIDField As Integer
        
        Private materialUOMField As String
        
        Private materialDescriptionField As String
        
        '''<remarks/>
        Public Property MaterialID() As Integer
            Get
                Return Me.materialIDField
            End Get
            Set
                Me.materialIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MaterialUOM() As String
            Get
                Return Me.materialUOMField
            End Get
            Set
                Me.materialUOMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MaterialDescription() As String
            Get
                Return Me.materialDescriptionField
            End Get
            Set
                Me.materialDescriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ProdItemBE
        
        Private prodItemNoField As Integer
        
        Private materialField As MaterialBE
        
        Private prodOrderField As ProdOrderBE
        
        Private productField As ProductBE
        
        Private uOMField As String
        
        Private quantityField As String
        
        Private remQtyField As String
        
        Private isCompletedField As Boolean
        
        Private responseStatusField As ResponseBE
        
        Private inventoryItemsField As System.Data.DataTable
        
        '''<remarks/>
        Public Property ProdItemNo() As Integer
            Get
                Return Me.prodItemNoField
            End Get
            Set
                Me.prodItemNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Material() As MaterialBE
            Get
                Return Me.materialField
            End Get
            Set
                Me.materialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProdOrder() As ProdOrderBE
            Get
                Return Me.prodOrderField
            End Get
            Set
                Me.prodOrderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Product() As ProductBE
            Get
                Return Me.productField
            End Get
            Set
                Me.productField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UOM() As String
            Get
                Return Me.uOMField
            End Get
            Set
                Me.uOMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Quantity() As String
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RemQty() As String
            Get
                Return Me.remQtyField
            End Get
            Set
                Me.remQtyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsCompleted() As Boolean
            Get
                Return Me.isCompletedField
            End Get
            Set
                Me.isCompletedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponseStatus() As ResponseBE
            Get
                Return Me.responseStatusField
            End Get
            Set
                Me.responseStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InventoryItems() As System.Data.DataTable
            Get
                Return Me.inventoryItemsField
            End Get
            Set
                Me.inventoryItemsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub GetProdItemsCompletedEventHandler(ByVal sender As Object, ByVal e As GetProdItemsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetProdItemsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResponseBE
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResponseBE)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub GetProdItemDetailsCompletedEventHandler(ByVal sender As Object, ByVal e As GetProdItemDetailsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetProdItemDetailsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ProdItemBE
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ProdItemBE)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub GetInvItemDetailsCompletedEventHandler(ByVal sender As Object, ByVal e As GetInvItemDetailsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetInvItemDetailsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As InvItemBE
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),InvItemBE)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub ProdItemAddTransactionCompletedEventHandler(ByVal sender As Object, ByVal e As ProdItemAddTransactionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProdItemAddTransactionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResponseBE
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResponseBE)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub ProdItemMoveCompletedEventHandler(ByVal sender As Object, ByVal e As ProdItemMoveCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProdItemMoveCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResponseBE
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResponseBE)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub UpdateProdOrderTimerCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateProdOrderTimerCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateProdOrderTimerCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResponseBE
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResponseBE)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PrintLabelL1CompletedEventHandler(ByVal sender As Object, ByVal e As PrintLabelL1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PrintLabelL1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResponseBE
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResponseBE)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PrintLabelL1FromAOSCompletedEventHandler(ByVal sender As Object, ByVal e As PrintLabelL1FromAOSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PrintLabelL1FromAOSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResponseBE
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResponseBE)
            End Get
        End Property
    End Class
End Namespace
