
USE [AOSData]
GO

/****** Object:  StoredProcedure [dbo].[proc_SHIPMENTLoadByPrimaryKey] Script Date: 12/10/2013 4:01:17 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_SHIPMENTLoadByPrimaryKey]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_SHIPMENTLoadByPrimaryKey];
GO

CREATE PROCEDURE [dbo].[proc_SHIPMENTLoadByPrimaryKey]
(
	@SHIPMENTNUMBER int
)
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @Err int

	SELECT
		[SHIPMENTNUMBER], 
		[SHIPMENTDATE], 
		[WORKORDERNUMBER], 
		[CUSTID], 
		[CUSTOMERNAME], 
		[SHIPFROMID], 
		[SHIPFROMNAME], 
		[SHIPFROMADDRESS1], 
		[SHIPFROMADDRESS2], 
		[SHIPFROMCITY], 
		[SHIPFROMSTATEPROV], 
		[SHIPFROMPOSTALCODE], 
		[SHIPFROMCOUNTRY], 
		[SHIPFROMPHONE], 
		[SHIPFROMFAX], 
		[SHIPFROMCONTACT], 
		[SHIPTOID], 
		[SHIPTONAME], 
		[SHIPTOADDRESS1], 
		[SHIPTOADDRESS2], 
		[SHIPTOCITY], 
		[SHIPTOSTATEPROV], 
		[SHIPTOPOSTALCODE], 
		[SHIPTOCOUNTRY], 
		[SHIPTOCONTACT], 
		[SHIPTOPHONE], 
		[CARRIERID], 
		[FREIGHTCARRIER], 
		[FOB], 
		[CUSTOMERPO], 
		[PLACARDSREQUIRED], 
		[PLACARDSSUPPLIED], 
		[SHIPMENTSTATUS], 
		[LOGISTICSID], 
		[COMMENTS], 
		[CREATEDBY], 
		[CREATEDTIME], 
		[MODIFYBY], 
		[MODIFYTIME]
	FROM [dbo].[SHIPMENT]
	WHERE
		([SHIPMENTNUMBER] = @SHIPMENTNUMBER)

	SET @Err = @@Error

	RETURN @Err
END
GO	


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_SHIPMENTLoadByPrimaryKey Succeeded'
ELSE PRINT 'Procedure Creation: proc_SHIPMENTLoadByPrimaryKey Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_SHIPMENTLoadAll] Script Date: 12/10/2013 4:01:17 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_SHIPMENTLoadAll]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_SHIPMENTLoadAll];
GO

CREATE PROCEDURE [dbo].[proc_SHIPMENTLoadAll]
AS
BEGIN

	SET NOCOUNT ON
	DECLARE @Err int

	SELECT
		[SHIPMENTNUMBER], 
		[SHIPMENTDATE], 
		[WORKORDERNUMBER], 
		[CUSTID], 
		[CUSTOMERNAME], 
		[SHIPFROMID], 
		[SHIPFROMNAME], 
		[SHIPFROMADDRESS1], 
		[SHIPFROMADDRESS2], 
		[SHIPFROMCITY], 
		[SHIPFROMSTATEPROV], 
		[SHIPFROMPOSTALCODE], 
		[SHIPFROMCOUNTRY], 
		[SHIPFROMPHONE], 
		[SHIPFROMFAX], 
		[SHIPFROMCONTACT], 
		[SHIPTOID], 
		[SHIPTONAME], 
		[SHIPTOADDRESS1], 
		[SHIPTOADDRESS2], 
		[SHIPTOCITY], 
		[SHIPTOSTATEPROV], 
		[SHIPTOPOSTALCODE], 
		[SHIPTOCOUNTRY], 
		[SHIPTOCONTACT], 
		[SHIPTOPHONE], 
		[CARRIERID], 
		[FREIGHTCARRIER], 
		[FOB], 
		[CUSTOMERPO], 
		[PLACARDSREQUIRED], 
		[PLACARDSSUPPLIED], 
		[SHIPMENTSTATUS], 
		[LOGISTICSID], 
		[COMMENTS], 
		[CREATEDBY], 
		[CREATEDTIME], 
		[MODIFYBY], 
		[MODIFYTIME]
	FROM [dbo].[SHIPMENT]

	SET @Err = @@Error

	RETURN @Err
END
GO


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_SHIPMENTLoadAll Succeeded'
ELSE PRINT 'Procedure Creation: proc_SHIPMENTLoadAll Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_SHIPMENTUpdate] Script Date: 12/10/2013 4:01:17 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_SHIPMENTUpdate]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_SHIPMENTUpdate];
GO

CREATE PROCEDURE [dbo].[proc_SHIPMENTUpdate]
(
	@SHIPMENTNUMBER int, 
	@SHIPMENTDATE datetime = NULL, 
	@WORKORDERNUMBER int = NULL, 
	@CUSTID int = NULL, 
	@CUSTOMERNAME varchar(50) = NULL, 
	@SHIPFROMID int = NULL, 
	@SHIPFROMNAME varchar(50) = NULL, 
	@SHIPFROMADDRESS1 varchar(50) = NULL, 
	@SHIPFROMADDRESS2 varchar(50) = NULL, 
	@SHIPFROMCITY varchar(50) = NULL, 
	@SHIPFROMSTATEPROV varchar(50) = NULL, 
	@SHIPFROMPOSTALCODE varchar(24) = NULL, 
	@SHIPFROMCOUNTRY varchar(50) = NULL, 
	@SHIPFROMPHONE varchar(50) = NULL, 
	@SHIPFROMFAX varchar(50) = NULL, 
	@SHIPFROMCONTACT varchar(50) = NULL, 
	@SHIPTOID int = NULL, 
	@SHIPTONAME varchar(50) = NULL, 
	@SHIPTOADDRESS1 varchar(50) = NULL, 
	@SHIPTOADDRESS2 varchar(50) = NULL, 
	@SHIPTOCITY varchar(50) = NULL, 
	@SHIPTOSTATEPROV varchar(50) = NULL, 
	@SHIPTOPOSTALCODE varchar(24) = NULL, 
	@SHIPTOCOUNTRY varchar(50) = NULL, 
	@SHIPTOCONTACT varchar(50) = NULL, 
	@SHIPTOPHONE varchar(50) = NULL, 
	@CARRIERID int = NULL, 
	@FREIGHTCARRIER varchar(50) = NULL, 
	@FOB varchar(24) = NULL, 
	@CUSTOMERPO varchar(50) = NULL, 
	@PLACARDSREQUIRED varchar(50) = NULL, 
	@PLACARDSSUPPLIED varchar(3) = NULL, 
	@SHIPMENTSTATUS varchar(50) = NULL, 
	@LOGISTICSID int = NULL, 
	@COMMENTS varchar(MAX) = NULL, 
	@CREATEDBY varchar(50) = NULL, 
	@CREATEDTIME datetime = NULL, 
	@MODIFYBY varchar(50) = NULL, 
	@MODIFYTIME datetime = NULL
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	UPDATE [SHIPMENT]
	SET
		[SHIPMENTDATE] = @SHIPMENTDATE, 
		[WORKORDERNUMBER] = @WORKORDERNUMBER, 
		[CUSTID] = @CUSTID, 
		[CUSTOMERNAME] = @CUSTOMERNAME, 
		[SHIPFROMID] = @SHIPFROMID, 
		[SHIPFROMNAME] = @SHIPFROMNAME, 
		[SHIPFROMADDRESS1] = @SHIPFROMADDRESS1, 
		[SHIPFROMADDRESS2] = @SHIPFROMADDRESS2, 
		[SHIPFROMCITY] = @SHIPFROMCITY, 
		[SHIPFROMSTATEPROV] = @SHIPFROMSTATEPROV, 
		[SHIPFROMPOSTALCODE] = @SHIPFROMPOSTALCODE, 
		[SHIPFROMCOUNTRY] = @SHIPFROMCOUNTRY, 
		[SHIPFROMPHONE] = @SHIPFROMPHONE, 
		[SHIPFROMFAX] = @SHIPFROMFAX, 
		[SHIPFROMCONTACT] = @SHIPFROMCONTACT, 
		[SHIPTOID] = @SHIPTOID, 
		[SHIPTONAME] = @SHIPTONAME, 
		[SHIPTOADDRESS1] = @SHIPTOADDRESS1, 
		[SHIPTOADDRESS2] = @SHIPTOADDRESS2, 
		[SHIPTOCITY] = @SHIPTOCITY, 
		[SHIPTOSTATEPROV] = @SHIPTOSTATEPROV, 
		[SHIPTOPOSTALCODE] = @SHIPTOPOSTALCODE, 
		[SHIPTOCOUNTRY] = @SHIPTOCOUNTRY, 
		[SHIPTOCONTACT] = @SHIPTOCONTACT, 
		[SHIPTOPHONE] = @SHIPTOPHONE, 
		[CARRIERID] = @CARRIERID, 
		[FREIGHTCARRIER] = @FREIGHTCARRIER, 
		[FOB] = @FOB, 
		[CUSTOMERPO] = @CUSTOMERPO, 
		[PLACARDSREQUIRED] = @PLACARDSREQUIRED, 
		[PLACARDSSUPPLIED] = @PLACARDSSUPPLIED, 
		[SHIPMENTSTATUS] = @SHIPMENTSTATUS, 
		[LOGISTICSID] = @LOGISTICSID, 
		[COMMENTS] = @COMMENTS, 
		[CREATEDBY] = @CREATEDBY, 
		[CREATEDTIME] = @CREATEDTIME, 
		[MODIFYBY] = @MODIFYBY, 
		[MODIFYTIME] = @MODIFYTIME
	WHERE
		([SHIPMENTNUMBER] = @SHIPMENTNUMBER)

	SET @Err = @@Error


	RETURN @Err
END
GO



-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_SHIPMENTUpdate Succeeded'
ELSE PRINT 'Procedure Creation: proc_SHIPMENTUpdate Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_SHIPMENTInsert] Script Date: 12/10/2013 4:01:17 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_SHIPMENTInsert]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_SHIPMENTInsert];
GO

CREATE PROCEDURE [dbo].[proc_SHIPMENTInsert]
(
	@SHIPMENTNUMBER int = NULL OUTPUT, 
	@SHIPMENTDATE datetime = NULL, 
	@WORKORDERNUMBER int = NULL, 
	@CUSTID int = NULL, 
	@CUSTOMERNAME varchar(50) = NULL, 
	@SHIPFROMID int = NULL, 
	@SHIPFROMNAME varchar(50) = NULL, 
	@SHIPFROMADDRESS1 varchar(50) = NULL, 
	@SHIPFROMADDRESS2 varchar(50) = NULL, 
	@SHIPFROMCITY varchar(50) = NULL, 
	@SHIPFROMSTATEPROV varchar(50) = NULL, 
	@SHIPFROMPOSTALCODE varchar(24) = NULL, 
	@SHIPFROMCOUNTRY varchar(50) = NULL, 
	@SHIPFROMPHONE varchar(50) = NULL, 
	@SHIPFROMFAX varchar(50) = NULL, 
	@SHIPFROMCONTACT varchar(50) = NULL, 
	@SHIPTOID int = NULL, 
	@SHIPTONAME varchar(50) = NULL, 
	@SHIPTOADDRESS1 varchar(50) = NULL, 
	@SHIPTOADDRESS2 varchar(50) = NULL, 
	@SHIPTOCITY varchar(50) = NULL, 
	@SHIPTOSTATEPROV varchar(50) = NULL, 
	@SHIPTOPOSTALCODE varchar(24) = NULL, 
	@SHIPTOCOUNTRY varchar(50) = NULL, 
	@SHIPTOCONTACT varchar(50) = NULL, 
	@SHIPTOPHONE varchar(50) = NULL, 
	@CARRIERID int = NULL, 
	@FREIGHTCARRIER varchar(50) = NULL, 
	@FOB varchar(24) = NULL, 
	@CUSTOMERPO varchar(50) = NULL, 
	@PLACARDSREQUIRED varchar(50) = NULL, 
	@PLACARDSSUPPLIED varchar(3) = NULL, 
	@SHIPMENTSTATUS varchar(50) = NULL, 
	@LOGISTICSID int = NULL, 
	@COMMENTS varchar(MAX) = NULL, 
	@CREATEDBY varchar(50) = NULL, 
	@CREATEDTIME datetime = NULL, 
	@MODIFYBY varchar(50) = NULL, 
	@MODIFYTIME datetime = NULL
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int
	

	INSERT
	INTO [SHIPMENT]
	(
		[SHIPMENTDATE], 
		[WORKORDERNUMBER], 
		[CUSTID], 
		[CUSTOMERNAME], 
		[SHIPFROMID], 
		[SHIPFROMNAME], 
		[SHIPFROMADDRESS1], 
		[SHIPFROMADDRESS2], 
		[SHIPFROMCITY], 
		[SHIPFROMSTATEPROV], 
		[SHIPFROMPOSTALCODE], 
		[SHIPFROMCOUNTRY], 
		[SHIPFROMPHONE], 
		[SHIPFROMFAX], 
		[SHIPFROMCONTACT], 
		[SHIPTOID], 
		[SHIPTONAME], 
		[SHIPTOADDRESS1], 
		[SHIPTOADDRESS2], 
		[SHIPTOCITY], 
		[SHIPTOSTATEPROV], 
		[SHIPTOPOSTALCODE], 
		[SHIPTOCOUNTRY], 
		[SHIPTOCONTACT], 
		[SHIPTOPHONE], 
		[CARRIERID], 
		[FREIGHTCARRIER], 
		[FOB], 
		[CUSTOMERPO], 
		[PLACARDSREQUIRED], 
		[PLACARDSSUPPLIED], 
		[SHIPMENTSTATUS], 
		[LOGISTICSID], 
		[COMMENTS], 
		[CREATEDBY], 
		[CREATEDTIME], 
		[MODIFYBY], 
		[MODIFYTIME]
	)
	
	VALUES
	(
		@SHIPMENTDATE, 
		@WORKORDERNUMBER, 
		@CUSTID, 
		@CUSTOMERNAME, 
		@SHIPFROMID, 
		@SHIPFROMNAME, 
		@SHIPFROMADDRESS1, 
		@SHIPFROMADDRESS2, 
		@SHIPFROMCITY, 
		@SHIPFROMSTATEPROV, 
		@SHIPFROMPOSTALCODE, 
		@SHIPFROMCOUNTRY, 
		@SHIPFROMPHONE, 
		@SHIPFROMFAX, 
		@SHIPFROMCONTACT, 
		@SHIPTOID, 
		@SHIPTONAME, 
		@SHIPTOADDRESS1, 
		@SHIPTOADDRESS2, 
		@SHIPTOCITY, 
		@SHIPTOSTATEPROV, 
		@SHIPTOPOSTALCODE, 
		@SHIPTOCOUNTRY, 
		@SHIPTOCONTACT, 
		@SHIPTOPHONE, 
		@CARRIERID, 
		@FREIGHTCARRIER, 
		@FOB, 
		@CUSTOMERPO, 
		@PLACARDSREQUIRED, 
		@PLACARDSSUPPLIED, 
		@SHIPMENTSTATUS, 
		@LOGISTICSID, 
		@COMMENTS, 
		@CREATEDBY, 
		@CREATEDTIME, 
		@MODIFYBY, 
		@MODIFYTIME
	)

	SET @Err = @@Error

		
	SELECT @SHIPMENTNUMBER = SCOPE_IDENTITY()

	

	RETURN @Err
END
GO


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_SHIPMENTInsert Succeeded'
ELSE PRINT 'Procedure Creation: proc_SHIPMENTInsert Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_SHIPMENTDelete] Script Date: 12/10/2013 4:01:17 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_SHIPMENTDelete]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_SHIPMENTDelete];
GO

CREATE PROCEDURE [dbo].[proc_SHIPMENTDelete]
(
	@SHIPMENTNUMBER int
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	DELETE
	FROM [dbo].[SHIPMENT]
	WHERE
		([SHIPMENTNUMBER] = @SHIPMENTNUMBER)

	SET @Err = @@Error

	RETURN @Err
END
GO


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_SHIPMENTDelete Succeeded'
ELSE PRINT 'Procedure Creation: proc_SHIPMENTDelete Error on Creation'
GO 

