
USE [AOSData]
GO

/****** Object:  StoredProcedure [dbo].[proc_WORKORDERLoadByPrimaryKey] Script Date: 12/10/2013 4:01:18 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_WORKORDERLoadByPrimaryKey]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_WORKORDERLoadByPrimaryKey];
GO

CREATE PROCEDURE [dbo].[proc_WORKORDERLoadByPrimaryKey]
(
	@WORKORDERNUMBER int
)
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @Err int

	SELECT
		[WORKORDERNUMBER], 
		[CUSTID], 
		[BILLADDRESS1], 
		[BILLADDRESS2], 
		[BILLCITY], 
		[BILLSTATEPROV], 
		[BILLPOSTALCODE], 
		[BILLCOUNTRY], 
		[BILLPHONE], 
		[BILLFAX], 
		[BILLCONTACT], 
		[SHIPADDRESS1], 
		[SHIPADDRESS2], 
		[SHIPCITY], 
		[SHIPSTATEPROV], 
		[SHIPPOSTALCODE], 
		[SHIPCOUNTRY], 
		[SHIPCONTACT], 
		[FREIGHTCARRIER], 
		[FOB], 
		[CUSTOMERPO], 
		[ORDERTERMS], 
		[DELIVERYDATE], 
		[PLANNEDSHIPDATE], 
		[HOWRECEIVED], 
		[ORDERSTATUS], 
		[ORDERNOTES], 
		[WORKORDERDATE], 
		[PREPAREDBY], 
		[SUPPLIERCOMPANY], 
		[SUBTOTAL], 
		[LOGISTICSID], 
		[CREATEDBY], 
		[CREATEDTIME], 
		[MODIFYBY], 
		[MODIFYTIME], 
		[SHIPPHONE], 
		[SHIPEMAIL], 
		[CARRIERID], 
		[WORKORDERTYPE], 
		[ONHOLD], 
		[ONHOLDREASON], 
		[FREIGHTCHARGES], 
		[FREIGHTBILLABLE], 
		[FREIGHTBILLCUSTOMER], 
		[FREIGHTONINVOICE], 
		[VENDORID]
	FROM [dbo].[WORKORDER]
	WHERE
		([WORKORDERNUMBER] = @WORKORDERNUMBER)

	SET @Err = @@Error

	RETURN @Err
END
GO	


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_WORKORDERLoadByPrimaryKey Succeeded'
ELSE PRINT 'Procedure Creation: proc_WORKORDERLoadByPrimaryKey Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_WORKORDERLoadAll] Script Date: 12/10/2013 4:01:18 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_WORKORDERLoadAll]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_WORKORDERLoadAll];
GO

CREATE PROCEDURE [dbo].[proc_WORKORDERLoadAll]
AS
BEGIN

	SET NOCOUNT ON
	DECLARE @Err int

	SELECT
		[WORKORDERNUMBER], 
		[CUSTID], 
		[BILLADDRESS1], 
		[BILLADDRESS2], 
		[BILLCITY], 
		[BILLSTATEPROV], 
		[BILLPOSTALCODE], 
		[BILLCOUNTRY], 
		[BILLPHONE], 
		[BILLFAX], 
		[BILLCONTACT], 
		[SHIPADDRESS1], 
		[SHIPADDRESS2], 
		[SHIPCITY], 
		[SHIPSTATEPROV], 
		[SHIPPOSTALCODE], 
		[SHIPCOUNTRY], 
		[SHIPCONTACT], 
		[FREIGHTCARRIER], 
		[FOB], 
		[CUSTOMERPO], 
		[ORDERTERMS], 
		[DELIVERYDATE], 
		[PLANNEDSHIPDATE], 
		[HOWRECEIVED], 
		[ORDERSTATUS], 
		[ORDERNOTES], 
		[WORKORDERDATE], 
		[PREPAREDBY], 
		[SUPPLIERCOMPANY], 
		[SUBTOTAL], 
		[LOGISTICSID], 
		[CREATEDBY], 
		[CREATEDTIME], 
		[MODIFYBY], 
		[MODIFYTIME], 
		[SHIPPHONE], 
		[SHIPEMAIL], 
		[CARRIERID], 
		[WORKORDERTYPE], 
		[ONHOLD], 
		[ONHOLDREASON], 
		[FREIGHTCHARGES], 
		[FREIGHTBILLABLE], 
		[FREIGHTBILLCUSTOMER], 
		[FREIGHTONINVOICE], 
		[VENDORID]
	FROM [dbo].[WORKORDER]

	SET @Err = @@Error

	RETURN @Err
END
GO


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_WORKORDERLoadAll Succeeded'
ELSE PRINT 'Procedure Creation: proc_WORKORDERLoadAll Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_WORKORDERUpdate] Script Date: 12/10/2013 4:01:18 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_WORKORDERUpdate]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_WORKORDERUpdate];
GO

CREATE PROCEDURE [dbo].[proc_WORKORDERUpdate]
(
	@WORKORDERNUMBER int, 
	@CUSTID int = NULL, 
	@BILLADDRESS1 varchar(50) = NULL, 
	@BILLADDRESS2 varchar(50) = NULL, 
	@BILLCITY varchar(50) = NULL, 
	@BILLSTATEPROV varchar(50) = NULL, 
	@BILLPOSTALCODE varchar(24) = NULL, 
	@BILLCOUNTRY varchar(50) = NULL, 
	@BILLPHONE varchar(50) = NULL, 
	@BILLFAX varchar(50) = NULL, 
	@BILLCONTACT varchar(50) = NULL, 
	@SHIPADDRESS1 varchar(50) = NULL, 
	@SHIPADDRESS2 varchar(50) = NULL, 
	@SHIPCITY varchar(50) = NULL, 
	@SHIPSTATEPROV varchar(50) = NULL, 
	@SHIPPOSTALCODE varchar(24) = NULL, 
	@SHIPCOUNTRY varchar(50) = NULL, 
	@SHIPCONTACT varchar(50) = NULL, 
	@FREIGHTCARRIER varchar(50) = NULL, 
	@FOB varchar(24) = NULL, 
	@CUSTOMERPO varchar(50) = NULL, 
	@ORDERTERMS varchar(50) = NULL, 
	@DELIVERYDATE datetime = NULL, 
	@PLANNEDSHIPDATE datetime = NULL, 
	@HOWRECEIVED varchar(24) = NULL, 
	@ORDERSTATUS varchar(50) = NULL, 
	@ORDERNOTES varchar(MAX) = NULL, 
	@WORKORDERDATE datetime = NULL, 
	@PREPAREDBY varchar(50) = NULL, 
	@SUPPLIERCOMPANY varchar(50) = NULL, 
	@SUBTOTAL money = NULL, 
	@LOGISTICSID int = NULL, 
	@CREATEDBY varchar(50) = NULL, 
	@CREATEDTIME datetime = NULL, 
	@MODIFYBY varchar(50) = NULL, 
	@MODIFYTIME datetime = NULL, 
	@SHIPPHONE varchar(50) = NULL, 
	@SHIPEMAIL varchar(50) = NULL, 
	@CARRIERID int = NULL, 
	@WORKORDERTYPE varchar(50) = NULL, 
	@ONHOLD bit = NULL, 
	@ONHOLDREASON varchar(200) = NULL, 
	@FREIGHTCHARGES decimal(18,4) = NULL, 
	@FREIGHTBILLABLE decimal(18,4) = NULL, 
	@FREIGHTBILLCUSTOMER bit = NULL, 
	@FREIGHTONINVOICE bit = NULL, 
	@VENDORID int = NULL
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	UPDATE [WORKORDER]
	SET
		[CUSTID] = @CUSTID, 
		[BILLADDRESS1] = @BILLADDRESS1, 
		[BILLADDRESS2] = @BILLADDRESS2, 
		[BILLCITY] = @BILLCITY, 
		[BILLSTATEPROV] = @BILLSTATEPROV, 
		[BILLPOSTALCODE] = @BILLPOSTALCODE, 
		[BILLCOUNTRY] = @BILLCOUNTRY, 
		[BILLPHONE] = @BILLPHONE, 
		[BILLFAX] = @BILLFAX, 
		[BILLCONTACT] = @BILLCONTACT, 
		[SHIPADDRESS1] = @SHIPADDRESS1, 
		[SHIPADDRESS2] = @SHIPADDRESS2, 
		[SHIPCITY] = @SHIPCITY, 
		[SHIPSTATEPROV] = @SHIPSTATEPROV, 
		[SHIPPOSTALCODE] = @SHIPPOSTALCODE, 
		[SHIPCOUNTRY] = @SHIPCOUNTRY, 
		[SHIPCONTACT] = @SHIPCONTACT, 
		[FREIGHTCARRIER] = @FREIGHTCARRIER, 
		[FOB] = @FOB, 
		[CUSTOMERPO] = @CUSTOMERPO, 
		[ORDERTERMS] = @ORDERTERMS, 
		[DELIVERYDATE] = @DELIVERYDATE, 
		[PLANNEDSHIPDATE] = @PLANNEDSHIPDATE, 
		[HOWRECEIVED] = @HOWRECEIVED, 
		[ORDERSTATUS] = @ORDERSTATUS, 
		[ORDERNOTES] = @ORDERNOTES, 
		[WORKORDERDATE] = @WORKORDERDATE, 
		[PREPAREDBY] = @PREPAREDBY, 
		[SUPPLIERCOMPANY] = @SUPPLIERCOMPANY, 
		[SUBTOTAL] = @SUBTOTAL, 
		[LOGISTICSID] = @LOGISTICSID, 
		[CREATEDBY] = @CREATEDBY, 
		[CREATEDTIME] = @CREATEDTIME, 
		[MODIFYBY] = @MODIFYBY, 
		[MODIFYTIME] = @MODIFYTIME, 
		[SHIPPHONE] = @SHIPPHONE, 
		[SHIPEMAIL] = @SHIPEMAIL, 
		[CARRIERID] = @CARRIERID, 
		[WORKORDERTYPE] = @WORKORDERTYPE, 
		[ONHOLD] = @ONHOLD, 
		[ONHOLDREASON] = @ONHOLDREASON, 
		[FREIGHTCHARGES] = @FREIGHTCHARGES, 
		[FREIGHTBILLABLE] = @FREIGHTBILLABLE, 
		[FREIGHTBILLCUSTOMER] = @FREIGHTBILLCUSTOMER, 
		[FREIGHTONINVOICE] = @FREIGHTONINVOICE, 
		[VENDORID] = @VENDORID
	WHERE
		([WORKORDERNUMBER] = @WORKORDERNUMBER)

	SET @Err = @@Error


	RETURN @Err
END
GO



-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_WORKORDERUpdate Succeeded'
ELSE PRINT 'Procedure Creation: proc_WORKORDERUpdate Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_WORKORDERInsert] Script Date: 12/10/2013 4:01:18 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_WORKORDERInsert]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_WORKORDERInsert];
GO

CREATE PROCEDURE [dbo].[proc_WORKORDERInsert]
(
	@WORKORDERNUMBER int = NULL OUTPUT, 
	@CUSTID int = NULL, 
	@BILLADDRESS1 varchar(50) = NULL, 
	@BILLADDRESS2 varchar(50) = NULL, 
	@BILLCITY varchar(50) = NULL, 
	@BILLSTATEPROV varchar(50) = NULL, 
	@BILLPOSTALCODE varchar(24) = NULL, 
	@BILLCOUNTRY varchar(50) = NULL, 
	@BILLPHONE varchar(50) = NULL, 
	@BILLFAX varchar(50) = NULL, 
	@BILLCONTACT varchar(50) = NULL, 
	@SHIPADDRESS1 varchar(50) = NULL, 
	@SHIPADDRESS2 varchar(50) = NULL, 
	@SHIPCITY varchar(50) = NULL, 
	@SHIPSTATEPROV varchar(50) = NULL, 
	@SHIPPOSTALCODE varchar(24) = NULL, 
	@SHIPCOUNTRY varchar(50) = NULL, 
	@SHIPCONTACT varchar(50) = NULL, 
	@FREIGHTCARRIER varchar(50) = NULL, 
	@FOB varchar(24) = NULL, 
	@CUSTOMERPO varchar(50) = NULL, 
	@ORDERTERMS varchar(50) = NULL, 
	@DELIVERYDATE datetime = NULL, 
	@PLANNEDSHIPDATE datetime = NULL, 
	@HOWRECEIVED varchar(24) = NULL, 
	@ORDERSTATUS varchar(50) = NULL, 
	@ORDERNOTES varchar(MAX) = NULL, 
	@WORKORDERDATE datetime = NULL, 
	@PREPAREDBY varchar(50) = NULL, 
	@SUPPLIERCOMPANY varchar(50) = NULL, 
	@SUBTOTAL money = NULL, 
	@LOGISTICSID int = NULL, 
	@CREATEDBY varchar(50) = NULL, 
	@CREATEDTIME datetime = NULL, 
	@MODIFYBY varchar(50) = NULL, 
	@MODIFYTIME datetime = NULL, 
	@SHIPPHONE varchar(50) = NULL, 
	@SHIPEMAIL varchar(50) = NULL, 
	@CARRIERID int = NULL, 
	@WORKORDERTYPE varchar(50) = NULL, 
	@ONHOLD bit = NULL, 
	@ONHOLDREASON varchar(200) = NULL, 
	@FREIGHTCHARGES decimal(18,4) = NULL, 
	@FREIGHTBILLABLE decimal(18,4) = NULL, 
	@FREIGHTBILLCUSTOMER bit = NULL, 
	@FREIGHTONINVOICE bit = NULL, 
	@VENDORID int = NULL
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int
	

	INSERT
	INTO [WORKORDER]
	(
		[CUSTID], 
		[BILLADDRESS1], 
		[BILLADDRESS2], 
		[BILLCITY], 
		[BILLSTATEPROV], 
		[BILLPOSTALCODE], 
		[BILLCOUNTRY], 
		[BILLPHONE], 
		[BILLFAX], 
		[BILLCONTACT], 
		[SHIPADDRESS1], 
		[SHIPADDRESS2], 
		[SHIPCITY], 
		[SHIPSTATEPROV], 
		[SHIPPOSTALCODE], 
		[SHIPCOUNTRY], 
		[SHIPCONTACT], 
		[FREIGHTCARRIER], 
		[FOB], 
		[CUSTOMERPO], 
		[ORDERTERMS], 
		[DELIVERYDATE], 
		[PLANNEDSHIPDATE], 
		[HOWRECEIVED], 
		[ORDERSTATUS], 
		[ORDERNOTES], 
		[WORKORDERDATE], 
		[PREPAREDBY], 
		[SUPPLIERCOMPANY], 
		[SUBTOTAL], 
		[LOGISTICSID], 
		[CREATEDBY], 
		[CREATEDTIME], 
		[MODIFYBY], 
		[MODIFYTIME], 
		[SHIPPHONE], 
		[SHIPEMAIL], 
		[CARRIERID], 
		[WORKORDERTYPE], 
		[ONHOLD], 
		[ONHOLDREASON], 
		[FREIGHTCHARGES], 
		[FREIGHTBILLABLE], 
		[FREIGHTBILLCUSTOMER], 
		[FREIGHTONINVOICE], 
		[VENDORID]
	)
	
	VALUES
	(
		@CUSTID, 
		@BILLADDRESS1, 
		@BILLADDRESS2, 
		@BILLCITY, 
		@BILLSTATEPROV, 
		@BILLPOSTALCODE, 
		@BILLCOUNTRY, 
		@BILLPHONE, 
		@BILLFAX, 
		@BILLCONTACT, 
		@SHIPADDRESS1, 
		@SHIPADDRESS2, 
		@SHIPCITY, 
		@SHIPSTATEPROV, 
		@SHIPPOSTALCODE, 
		@SHIPCOUNTRY, 
		@SHIPCONTACT, 
		@FREIGHTCARRIER, 
		@FOB, 
		@CUSTOMERPO, 
		@ORDERTERMS, 
		@DELIVERYDATE, 
		@PLANNEDSHIPDATE, 
		@HOWRECEIVED, 
		@ORDERSTATUS, 
		@ORDERNOTES, 
		@WORKORDERDATE, 
		@PREPAREDBY, 
		@SUPPLIERCOMPANY, 
		@SUBTOTAL, 
		@LOGISTICSID, 
		@CREATEDBY, 
		@CREATEDTIME, 
		@MODIFYBY, 
		@MODIFYTIME, 
		@SHIPPHONE, 
		@SHIPEMAIL, 
		@CARRIERID, 
		@WORKORDERTYPE, 
		@ONHOLD, 
		@ONHOLDREASON, 
		@FREIGHTCHARGES, 
		@FREIGHTBILLABLE, 
		@FREIGHTBILLCUSTOMER, 
		@FREIGHTONINVOICE, 
		@VENDORID
	)

	SET @Err = @@Error

		
	SELECT @WORKORDERNUMBER = SCOPE_IDENTITY()

	

	RETURN @Err
END
GO


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_WORKORDERInsert Succeeded'
ELSE PRINT 'Procedure Creation: proc_WORKORDERInsert Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_WORKORDERDelete] Script Date: 12/10/2013 4:01:18 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_WORKORDERDelete]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_WORKORDERDelete];
GO

CREATE PROCEDURE [dbo].[proc_WORKORDERDelete]
(
	@WORKORDERNUMBER int
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	DELETE
	FROM [dbo].[WORKORDER]
	WHERE
		([WORKORDERNUMBER] = @WORKORDERNUMBER)

	SET @Err = @@Error

	RETURN @Err
END
GO


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_WORKORDERDelete Succeeded'
ELSE PRINT 'Procedure Creation: proc_WORKORDERDelete Error on Creation'
GO 

