
USE [AOSData]
GO

/****** Object:  StoredProcedure [dbo].[proc_WORKORDERITEMLoadByPrimaryKey] Script Date: 12/10/2013 4:01:18 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_WORKORDERITEMLoadByPrimaryKey]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_WORKORDERITEMLoadByPrimaryKey];
GO

CREATE PROCEDURE [dbo].[proc_WORKORDERITEMLoadByPrimaryKey]
(
	@WORKORDERITEMNUMBER int
)
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @Err int

	SELECT
		[WORKORDERITEMNUMBER], 
		[WORKORDERNUMBER], 
		[PRODUCTID], 
		[PRODUCTDESC], 
		[CONTAINER], 
		[QTY], 
		[INVITEMNUMBER], 
		[ITEMCOMMENTS], 
		[LOTNUMBER], 
		[WAREHOUSELOCATION], 
		[BILLABLE], 
		[UNITCOST], 
		[ITEMPRICE], 
		[ITEMPROFIT], 
		[UNITORCONTAINER], 
		[UNITS], 
		[UOM], 
		[EXTPRICE], 
		[EXTCOST], 
		[EXTPROFIT], 
		[SOURCETYPE], 
		[SOURCEDOCUMENT], 
		[WORKORDERITEMSTATUS], 
		[CUSTOMERPO], 
		[SHIPMENTITEMNUMBER], 
		[INVOICEITEMNUMBER], 
		[ITEMTYPE]
	FROM [dbo].[WORKORDERITEM]
	WHERE
		([WORKORDERITEMNUMBER] = @WORKORDERITEMNUMBER)

	SET @Err = @@Error

	RETURN @Err
END
GO	


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_WORKORDERITEMLoadByPrimaryKey Succeeded'
ELSE PRINT 'Procedure Creation: proc_WORKORDERITEMLoadByPrimaryKey Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_WORKORDERITEMLoadAll] Script Date: 12/10/2013 4:01:18 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_WORKORDERITEMLoadAll]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_WORKORDERITEMLoadAll];
GO

CREATE PROCEDURE [dbo].[proc_WORKORDERITEMLoadAll]
AS
BEGIN

	SET NOCOUNT ON
	DECLARE @Err int

	SELECT
		[WORKORDERITEMNUMBER], 
		[WORKORDERNUMBER], 
		[PRODUCTID], 
		[PRODUCTDESC], 
		[CONTAINER], 
		[QTY], 
		[INVITEMNUMBER], 
		[ITEMCOMMENTS], 
		[LOTNUMBER], 
		[WAREHOUSELOCATION], 
		[BILLABLE], 
		[UNITCOST], 
		[ITEMPRICE], 
		[ITEMPROFIT], 
		[UNITORCONTAINER], 
		[UNITS], 
		[UOM], 
		[EXTPRICE], 
		[EXTCOST], 
		[EXTPROFIT], 
		[SOURCETYPE], 
		[SOURCEDOCUMENT], 
		[WORKORDERITEMSTATUS], 
		[CUSTOMERPO], 
		[SHIPMENTITEMNUMBER], 
		[INVOICEITEMNUMBER], 
		[ITEMTYPE]
	FROM [dbo].[WORKORDERITEM]

	SET @Err = @@Error

	RETURN @Err
END
GO


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_WORKORDERITEMLoadAll Succeeded'
ELSE PRINT 'Procedure Creation: proc_WORKORDERITEMLoadAll Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_WORKORDERITEMUpdate] Script Date: 12/10/2013 4:01:18 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_WORKORDERITEMUpdate]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_WORKORDERITEMUpdate];
GO

CREATE PROCEDURE [dbo].[proc_WORKORDERITEMUpdate]
(
	@WORKORDERITEMNUMBER int, 
	@WORKORDERNUMBER int, 
	@PRODUCTID int = NULL, 
	@PRODUCTDESC varchar(200) = NULL, 
	@CONTAINER varchar(50) = NULL, 
	@QTY numeric(18,4) = NULL, 
	@INVITEMNUMBER int = NULL, 
	@ITEMCOMMENTS varchar(MAX) = NULL, 
	@LOTNUMBER varchar(50) = NULL, 
	@WAREHOUSELOCATION varchar(50) = NULL, 
	@BILLABLE bit = NULL, 
	@UNITCOST decimal(18,4) = NULL, 
	@ITEMPRICE decimal(18,4) = NULL, 
	@ITEMPROFIT decimal(18,4) = NULL, 
	@UNITORCONTAINER varchar(1) = NULL, 
	@UNITS int = NULL, 
	@UOM varchar(8) = NULL, 
	@EXTPRICE decimal(18,4) = NULL, 
	@EXTCOST decimal(18,4) = NULL, 
	@EXTPROFIT decimal(18,4) = NULL, 
	@SOURCETYPE varchar(50) = NULL, 
	@SOURCEDOCUMENT int = NULL, 
	@WORKORDERITEMSTATUS varchar(50) = NULL, 
	@CUSTOMERPO varchar(50) = NULL, 
	@SHIPMENTITEMNUMBER int = NULL, 
	@INVOICEITEMNUMBER int = NULL, 
	@ITEMTYPE varchar(50) = NULL
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	UPDATE [WORKORDERITEM]
	SET
		[WORKORDERNUMBER] = @WORKORDERNUMBER, 
		[PRODUCTID] = @PRODUCTID, 
		[PRODUCTDESC] = @PRODUCTDESC, 
		[CONTAINER] = @CONTAINER, 
		[QTY] = @QTY, 
		[INVITEMNUMBER] = @INVITEMNUMBER, 
		[ITEMCOMMENTS] = @ITEMCOMMENTS, 
		[LOTNUMBER] = @LOTNUMBER, 
		[WAREHOUSELOCATION] = @WAREHOUSELOCATION, 
		[BILLABLE] = @BILLABLE, 
		[UNITCOST] = @UNITCOST, 
		[ITEMPRICE] = @ITEMPRICE, 
		[ITEMPROFIT] = @ITEMPROFIT, 
		[UNITORCONTAINER] = @UNITORCONTAINER, 
		[UNITS] = @UNITS, 
		[UOM] = @UOM, 
		[EXTPRICE] = @EXTPRICE, 
		[EXTCOST] = @EXTCOST, 
		[EXTPROFIT] = @EXTPROFIT, 
		[SOURCETYPE] = @SOURCETYPE, 
		[SOURCEDOCUMENT] = @SOURCEDOCUMENT, 
		[WORKORDERITEMSTATUS] = @WORKORDERITEMSTATUS, 
		[CUSTOMERPO] = @CUSTOMERPO, 
		[SHIPMENTITEMNUMBER] = @SHIPMENTITEMNUMBER, 
		[INVOICEITEMNUMBER] = @INVOICEITEMNUMBER, 
		[ITEMTYPE] = @ITEMTYPE
	WHERE
		([WORKORDERITEMNUMBER] = @WORKORDERITEMNUMBER)

	SET @Err = @@Error


	RETURN @Err
END
GO



-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_WORKORDERITEMUpdate Succeeded'
ELSE PRINT 'Procedure Creation: proc_WORKORDERITEMUpdate Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_WORKORDERITEMInsert] Script Date: 12/10/2013 4:01:18 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_WORKORDERITEMInsert]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_WORKORDERITEMInsert];
GO

CREATE PROCEDURE [dbo].[proc_WORKORDERITEMInsert]
(
	@WORKORDERITEMNUMBER int = NULL OUTPUT, 
	@WORKORDERNUMBER int, 
	@PRODUCTID int = NULL, 
	@PRODUCTDESC varchar(200) = NULL, 
	@CONTAINER varchar(50) = NULL, 
	@QTY numeric(18,4) = NULL, 
	@INVITEMNUMBER int = NULL, 
	@ITEMCOMMENTS varchar(MAX) = NULL, 
	@LOTNUMBER varchar(50) = NULL, 
	@WAREHOUSELOCATION varchar(50) = NULL, 
	@BILLABLE bit = NULL, 
	@UNITCOST decimal(18,4) = NULL, 
	@ITEMPRICE decimal(18,4) = NULL, 
	@ITEMPROFIT decimal(18,4) = NULL, 
	@UNITORCONTAINER varchar(1) = NULL, 
	@UNITS int = NULL, 
	@UOM varchar(8) = NULL, 
	@EXTPRICE decimal(18,4) = NULL, 
	@EXTCOST decimal(18,4) = NULL, 
	@EXTPROFIT decimal(18,4) = NULL, 
	@SOURCETYPE varchar(50) = NULL, 
	@SOURCEDOCUMENT int = NULL, 
	@WORKORDERITEMSTATUS varchar(50) = NULL, 
	@CUSTOMERPO varchar(50) = NULL, 
	@SHIPMENTITEMNUMBER int = NULL, 
	@INVOICEITEMNUMBER int = NULL, 
	@ITEMTYPE varchar(50) = NULL
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int
	

	INSERT
	INTO [WORKORDERITEM]
	(
		[WORKORDERNUMBER], 
		[PRODUCTID], 
		[PRODUCTDESC], 
		[CONTAINER], 
		[QTY], 
		[INVITEMNUMBER], 
		[ITEMCOMMENTS], 
		[LOTNUMBER], 
		[WAREHOUSELOCATION], 
		[BILLABLE], 
		[UNITCOST], 
		[ITEMPRICE], 
		[ITEMPROFIT], 
		[UNITORCONTAINER], 
		[UNITS], 
		[UOM], 
		[EXTPRICE], 
		[EXTCOST], 
		[EXTPROFIT], 
		[SOURCETYPE], 
		[SOURCEDOCUMENT], 
		[WORKORDERITEMSTATUS], 
		[CUSTOMERPO], 
		[SHIPMENTITEMNUMBER], 
		[INVOICEITEMNUMBER], 
		[ITEMTYPE]
	)
	
	VALUES
	(
		@WORKORDERNUMBER, 
		@PRODUCTID, 
		@PRODUCTDESC, 
		@CONTAINER, 
		@QTY, 
		@INVITEMNUMBER, 
		@ITEMCOMMENTS, 
		@LOTNUMBER, 
		@WAREHOUSELOCATION, 
		@BILLABLE, 
		@UNITCOST, 
		@ITEMPRICE, 
		@ITEMPROFIT, 
		@UNITORCONTAINER, 
		@UNITS, 
		@UOM, 
		@EXTPRICE, 
		@EXTCOST, 
		@EXTPROFIT, 
		@SOURCETYPE, 
		@SOURCEDOCUMENT, 
		@WORKORDERITEMSTATUS, 
		@CUSTOMERPO, 
		@SHIPMENTITEMNUMBER, 
		@INVOICEITEMNUMBER, 
		@ITEMTYPE
	)

	SET @Err = @@Error

		
	SELECT @WORKORDERITEMNUMBER = SCOPE_IDENTITY()

	

	RETURN @Err
END
GO


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_WORKORDERITEMInsert Succeeded'
ELSE PRINT 'Procedure Creation: proc_WORKORDERITEMInsert Error on Creation'
GO 


/****** Object:  StoredProcedure [dbo].[proc_WORKORDERITEMDelete] Script Date: 12/10/2013 4:01:18 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[proc_WORKORDERITEMDelete]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[proc_WORKORDERITEMDelete];
GO

CREATE PROCEDURE [dbo].[proc_WORKORDERITEMDelete]
(
	@WORKORDERITEMNUMBER int
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	DELETE
	FROM [dbo].[WORKORDERITEM]
	WHERE
		([WORKORDERITEMNUMBER] = @WORKORDERITEMNUMBER)

	SET @Err = @@Error

	RETURN @Err
END
GO


-- Display the status of Proc creation
IF (@@Error = 0) PRINT 'Procedure Creation: proc_WORKORDERITEMDelete Succeeded'
ELSE PRINT 'Procedure Creation: proc_WORKORDERITEMDelete Error on Creation'
GO 

